### ISSUE TITLE
盒子内运行半糖，分享微信有一定几率报错

### ISSUE THREAD

**Issue by imilk** [asLody/VirtualApp#10]
07-13 14:29:00.961 17763-17763/com.jzyd.BanTang:pushservice E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.jzyd.BanTang:pushservice, PID: 17763
                                                                              java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.tencent.mm/com.tencent.mm.ui.LauncherUI}: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.ui.LauncherUI" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
                                                                                  at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:158)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                               Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.mm.ui.LauncherUI" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                                  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                  at android.app.Instrumentation.newActivity(Instrumentation.java:1095)
                                                                                  at com.lody.virtual.client.hook.delegate.InstrumentationDelegate.newActivity(InstrumentationDelegate.java:253)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3084)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                                  at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:158) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:7237) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                              	Suppressed: java.lang.ClassNotFoundException: com.tencent.mm.ui.LauncherUI
                                                                                  at java.lang.Class.classForName(Native Method)
                                                                                  at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                  at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                  		... 13 more
                                                                               Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by imilk** [comment]
经简单测试，为交替运行两个app回退页面时报的错
