### ISSUE TITLE
三星s6第一次进入微信时报错ConcurrentModificationException

### ISSUE THREAD

**Issue by tjt852** [asLody/VirtualApp#106]
09-13 15:48:15.971 31491-31491/io.virtualapp:x E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: io.virtualapp:x, PID: 31491
                                                                 java.util.ConcurrentModificationException
                                                                     at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
                                                                     at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:964)
                                                                     at com.lody.virtual.service.am.ActivityStack$1.run(ActivityStack.java:60)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:158)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

![mo1 x c y9h2n _ x9is w](https://cloud.githubusercontent.com/assets/5794936/18465588/0e23fa5c-79ca-11e6-978a-4b58efc7a881.png)

**Comment by tjt852** [comment]
第二次进入就可以了，，，但是第一次发送一条消息，也报这个异常

**Comment by asLody** [comment]
Fixed.
