### ISSUE TITLE
Crashes on Android N

### ISSUE THREAD

**Issue by FD-** [asLody/VirtualApp#113]
When I try to start a virtual app inside VirtualApp on Nougat (Nexus 9), VirtualApp crashes. I see this exception in logcat:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: io.virtualapp:p0, PID: 31161
                                                                  java.lang.ExceptionInInitializerError
                                                                      at com.lody.virtual.IOHook.onGetUid(IOHook.java:162)
                                                                      at com.lody.virtual.client.hook.patchs.libcore.GetUid.afterCall(GetUid.java:21)
                                                                      at com.lody.virtual.client.hook.base.HookDelegate$HookHandler.invoke(HookDelegate.java:160)
                                                                      at java.lang.reflect.Proxy.invoke(Proxy.java:813)
                                                                      at $Proxy2.getuid(Unknown Source)
                                                                      at android.system.Os.getuid(Os.java:222)
                                                                      at android.os.Process.myUid(Process.java:835)
                                                                      at android.content.ContentProvider.attachInfo(ContentProvider.java:1742)
                                                                      at android.content.ContentProvider.attachInfo(ContentProvider.java:1726)
                                                                      at android.app.ActivityThread.installProvider(ActivityThread.java:5811)
                                                                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:5403)
                                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5342)
                                                                      at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                   Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: openDexFileNative [class java.lang.String, class java.lang.String, int]
                                                                      at com.lody.virtual.IOHook.<clinit>(IOHook.java:95)
                                                                      at com.lody.virtual.IOHook.onGetUid(IOHook.java:162) 
                                                                      at com.lody.virtual.client.hook.patchs.libcore.GetUid.afterCall(GetUid.java:21) 
                                                                      at com.lody.virtual.client.hook.base.HookDelegate$HookHandler.invoke(HookDelegate.java:160) 
                                                                      at java.lang.reflect.Proxy.invoke(Proxy.java:813) 
                                                                      at $Proxy2.getuid(Unknown Source) 
                                                                      at android.system.Os.getuid(Os.java:222) 
                                                                      at android.os.Process.myUid(Process.java:835) 
                                                                      at android.content.ContentProvider.attachInfo(ContentProvider.java:1742) 
                                                                      at android.content.ContentProvider.attachInfo(ContentProvider.java:1726) 
                                                                      at android.app.ActivityThread.installProvider(ActivityThread.java:5811) 
                                                                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:5403) 
                                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5342) 
                                                                      at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:154) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                   Caused by: java.lang.NoSuchMethodException: openDexFileNative [class java.lang.String, class java.lang.String, int]
                                                                      at java.lang.Class.getMethod(Class.java:1981)
                                                                      at java.lang.Class.getDeclaredMethod(Class.java:1960)
                                                                      at com.lody.virtual.IOHook.<clinit>(IOHook.java:92)
                                                                      at com.lody.virtual.IOHook.onGetUid(IOHook.java:162) 
                                                                      at com.lody.virtual.client.hook.patchs.libcore.GetUid.afterCall(GetUid.java:21) 
                                                                      at com.lody.virtual.client.hook.base.HookDelegate$HookHandler.invoke(HookDelegate.java:160) 
                                                                      at java.lang.reflect.Proxy.invoke(Proxy.java:813) 
                                                                      at $Proxy2.getuid(Unknown Source) 
                                                                      at android.system.Os.getuid(Os.java:222) 
                                                                      at android.os.Process.myUid(Process.java:835) 
                                                                      at android.content.ContentProvider.attachInfo(ContentProvider.java:1742) 
                                                                      at android.content.ContentProvider.attachInfo(ContentProvider.java:1726) 
                                                                      at android.app.ActivityThread.installProvider(ActivityThread.java:5811) 
                                                                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:5403) 
                                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5342) 
                                                                      at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:154) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
```

Do you have plans to add support for Android N? Or is this maybe caused by the Nexus 9's CPU being ARM 64 bit?

**Comment by asLody** [comment]
In progress.

**Comment by asLody** [comment]
Done.
