### ISSUE TITLE
最近代码在测试时更新双开应用会报java.lang.VerifyError错误

### ISSUE THREAD

**Issue by piersguo** [asLody/VirtualApp#117]
在更新最新代码后，发现在重新安装VA应用包，或者在VA中双开的应用进行更新升级时，会报如下错误：
09-21 16:02:48.955 E/AndroidRuntime( 8315): FATAL EXCEPTION: main
09-21 16:02:48.955 E/AndroidRuntime( 8315): java.lang.VerifyError: com/lody/virtual/helper/utils/FileUtils
09-21 16:02:48.955 E/AndroidRuntime( 8315): 	at com.lody.virtual.server.pm.VAppManagerService.preloadAllApps(VAppManagerService.java:98)
09-21 16:02:48.955 E/AndroidRuntime( 8315): 	at com.lody.virtual.server.pm.VAppManagerService.systemReady(VAppManagerService.java:70)
09-21 16:02:48.955 E/AndroidRuntime( 8315): 	at com.lody.virtual.server.BinderProvider.onCreate(BinderProvider.java:42)
09-21 16:02:48.955 E/AndroidRuntime( 8315): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1591)
09-21 16:02:48.955 E/AndroidRuntime( 8315): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1562)
09-21 16:02:48.955 E/AndroidRuntime( 8315): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4840)
09-21 16:02:48.955 E/AndroidRuntime( 8315): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4435)
09-21 16:02:48.955 E/AndroidRuntime( 8315): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4375)
09-21 16:02:48.955 E/AndroidRuntime( 8315): 	at android.app.ActivityThread.access$1600(ActivityThread.java:141)
09-21 16:02:48.955 E/AndroidRuntime( 8315): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1273)
09-21 16:02:48.955 E/AndroidRuntime( 8315): 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-21 16:02:48.955 E/AndroidRuntime( 8315): 	at android.os.Looper.loop(Looper.java:136)
09-21 16:02:48.955 E/AndroidRuntime( 8315): 	at android.app.ActivityThread.main(ActivityThread.java:5072)
09-21 16:02:48.955 E/AndroidRuntime( 8315): 	at java.lang.reflect.Method.invokeNative(Native Method)
09-21 16:02:48.955 E/AndroidRuntime( 8315): 	at java.lang.reflect.Method.invoke(Method.java:515)
09-21 16:02:48.955 E/AndroidRuntime( 8315): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
09-21 16:02:48.955 E/AndroidRuntime( 8315): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
09-21 16:02:48.955 E/AndroidRuntime( 8315): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by piersguo** [comment]
今天最新代码已经fix
