### ISSUE TITLE
小米手机6.0.1 打开Tumblr ,KakaoTalk通讯软件必现crash

### ISSUE THREAD

**Issue by renqingyou** [asLody/VirtualApp#118]

**Comment by renqingyou** [comment]
09-21 17:26:48.156 6453-6537/? E/AppOpsAdapter:  doApplyAppPermissionConfig error 
                                                android.content.pm.PackageManager$NameNotFoundException: com.drderico.kakao
                                                    at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:304)
                                                    at com.lbe.security.service.provider.internal.AppOpsAdapter$AppOpsAdapterHandler.doApplyAppPermissionConfig(AppOpsAdapter.java:100)
                                                    at com.lbe.security.service.provider.internal.AppOpsAdapter$AppOpsAdapterHandler.handleMessage(AppOpsAdapter.java:73)
                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                    at android.os.Looper.loop(Looper.java:148)
                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
09-21 17:26:49.175 13851-13899/? E/MarketDataParser: [AppList] JSON : list is null
                                                     org.json.JSONException: No value for miuiApp
                                                         at org.json.JSONObject.get(JSONObject.java:389)
                                                         at org.json.JSONObject.getJSONArray(JSONObject.java:584)
                                                         at com.xiaomi.market.data.p.a(DataParser.java:229)
                                                         at com.xiaomi.market.data.p.b(DataParser.java:1430)
                                                         at com.xiaomi.market.data.bf.a(LocalAppManager.java:982)
                                                         at com.xiaomi.market.data.bf.doInBackground(LocalAppManager.java:928)
                                                         at com.xiaomi.market.data.bf.doInBackground(LocalAppManager.java:828)
                                                         at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                         at java.lang.Thread.run(Thread.java:818)
09-21 17:27:13.130 15500-15500/io.virtualapp:p3 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.kakao.talk, PID: 15500
                                                                  java.lang.RuntimeException: Unable to create application o.ﺙ: java.lang.SecurityException: Proxy package io.virtualapp from uid 10011 or calling package com.kakao.talk from uid 10011 not allowed to perform OP_READ_PHONE_STATE
                                                                      at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:297)
                                                                      at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:188)
                                                                      at com.lody.virtual.client.hook.patchs.am.HCallbackHook.handleLaunchActivity(HCallbackHook.java:109)
                                                                      at com.lody.virtual.client.hook.patchs.am.HCallbackHook.handleMessage(HCallbackHook.java:69)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                                   Caused by: java.lang.SecurityException: Proxy package io.virtualapp from uid 10011 or calling package com.kakao.talk from uid 10011 not allowed to perform OP_READ_PHONE_STATE
                                                                      at android.app.AppOpsManager.noteProxyOp(AppOpsManager.java:1724)
                                                                      at android.app.AppOpsManager.noteProxyOp(AppOpsManager.java:1539)
                                                                      at o.ᵔ.ˊ(:37)
                                                                      at o.ᵎ$if.ˊ(:77)
                                                                      at o.ᵎ.ˊ(:140)
                                                                      at o.ˎ.ˊ(:4106)
                                                                      at o.zb.ˊ(:27)
                                                                      at o.zb.ˊ(:20)
                                                                      at o.ﺙ.onCreate(:4356)
                                                                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                                                                      at com.lody.virtual.client.hook.delegate.InstrumentationDelegate.callApplicationOnCreate(InstrumentationDelegate.java:230)
                                                                      at com.lody.virtual.client.hook.delegate.AppInstrumentation.callApplicationOnCreate(AppInstrumentation.java:104)
                                                                      at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:289)
                                                                      at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:188) 
                                                                      at com.lody.virtual.client.hook.patchs.am.HCallbackHook.handleLaunchActivity(HCallbackHook.java:109) 
                                                                      at com.lody.virtual.client.hook.patchs.am.HCallbackHook.handleMessage(HCallbackHook.java:69) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5438) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
09-21 17:28:51.765 15754-15754/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.kakao.talk, PID: 15754
                                                   java.lang.RuntimeException: Unable to create application o.ﺙ: java.lang.SecurityException: Proxy package io.virtualapp from uid 10011 or calling package com.kakao.talk from uid 10011 not allowed to perform OP_READ_PHONE_STATE
                                                       at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:297)
                                                       at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:188)
                                                       at com.lody.virtual.client.hook.patchs.am.HCallbackHook.handleLaunchActivity(HCallbackHook.java:109)
                                                       at com.lody.virtual.client.hook.patchs.am.HCallbackHook.handleMessage(HCallbackHook.java:69)
                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                    Caused by: java.lang.SecurityException: Proxy package io.virtualapp from uid 10011 or calling package com.kakao.talk from uid 10011 not allowed to perform OP_READ_PHONE_STATE
                                                       at android.app.AppOpsManager.noteProxyOp(AppOpsManager.java:1724)
                                                       at android.app.AppOpsManager.noteProxyOp(AppOpsManager.java:1539)
                                                       at o.ᵔ.ˊ(:37)
                                                       at o.ᵎ$if.ˊ(:77)
                                                       at o.ᵎ.ˊ(:140)
                                                       at o.ˎ.ˊ(:4106)
                                                       at o.zb.ˊ(:27)
                                                       at o.zb.ˊ(:20)
                                                       at o.ﺙ.onCreate(:4356)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                                                       at com.lody.virtual.client.hook.delegate.InstrumentationDelegate.callApplicationOnCreate(InstrumentationDelegate.java:230)
                                                       at com.lody.virtual.client.hook.delegate.AppInstrumentation.callApplicationOnCreate(AppInstrumentation.java:104)
                                                       at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:289)
                                                       at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:188) 
                                                       at com.lody.virtual.client.hook.patchs.am.HCallbackHook.handleLaunchActivity(HCallbackHook.java:109) 
                                                       at com.lody.virtual.client.hook.patchs.am.HCallbackHook.handleMessage(HCallbackHook.java:69) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5438) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
