### ISSUE TITLE
打开facebook，报相册停止运行，还报 VirtualApp停止运行

### ISSUE THREAD

**Issue by renqingyou** [asLody/VirtualApp#125]
09-23 16:54:49.221 28789-28789/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.sec.android.gallery3d, PID: 28789
                                                   java.lang.RuntimeException: Unable to start receiver com.sec.android.gallery3d.picasa.PicasaSyncAdapter$AccountChangeReceiver: java.lang.NullPointerException
                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2590)
                                                       at android.app.ActivityThread.access$1800(ActivityThread.java:169)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5476)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.NullPointerException
                                                       at com.sec.android.gallery3d.picasa.PicasaSyncAdapter$AccountChangeReceiver.onReceive(PicasaSyncAdapter.java:100)
                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2575)
                                                       at android.app.ActivityThread.access$1800(ActivityThread.java:169) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5476) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
09-23 16:54:49.361 7286-7286/? E/dalvikvm: >>>>> Normal User

**Comment by renqingyou** [comment]
5-17605/com.security.multiple.account.applock:p1 E/l: Handing uncaught exception
                                                                             java.lang.RuntimeException: Error receiving broadcast Intent { act=com.facebook.zero.ACTION_ZERO_REFRESH_TOKEN pkg=com.facebook.katana (has extras) } in com.facebook.base.broadcast.d@4fe957
                                                                                 at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java)
                                                                                 at android.os.Handler.handleCallback(Handler.java)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java)
                                                                                 at android.os.Looper.loop(Looper.java)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
                                                                              Caused by: java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = com.facebook.zero.sdk.common.TokenRequestReason)
                                                                                 at android.os.Parcel.readSerializable(Parcel.java)
                                                                                 at android.os.Parcel.readValue(Parcel.java)
                                                                                 at android.os.Parcel.readArrayMapInternal(Parcel.java)
                                                                                 at android.os.BaseBundle.unparcel(BaseBundle.java)
                                                                                 at android.os.BaseBundle.getSerializable(BaseBundle.java)
                                                                                 at android.os.Bundle.getSerializable(Bundle.java)
                                                                                 at android.content.Intent.getSerializableExtra(Intent.java)
                                                                                 at com.facebook.zero.k.o.onReceive(:189345)
                                                                                 at com.facebook.common.init.n.onReceive(:58756)
                                                                                 at com.facebook.content.w.onReceive(:64476)
                                                                                 at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java) 
                                                                                 at android.os.Handler.handleCallback(Handler.java) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java) 
                                                                                 at android.os.Looper.loop(Looper.java) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java) 
                                                                              Caused by: java.lang.ClassNotFoundException: com.facebook.zero.sdk.common.TokenRequestReason
                                                                                 at java.lang.Class.classForName(Native Method)
                                                                                 at java.lang.Class.forName(Class.java:324)
                                                                                 at android.os.Parcel$2.resolveClass(Parcel.java)
                                                                                 at java.io.ObjectInputStream.readEnumDescInternal(ObjectInputStream.java:1551)
                                                                                 at java.io.ObjectInputStream.readEnumDesc(ObjectInputStream.java:1532)
                                                                                 at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1577)
                                                                                 at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:767)
                                                                                 at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
                                                                                 at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
                                                                                 at android.os.Parcel.readSerializable(Parcel.java) 
                                                                                 at android.os.Parcel.readValue(Parcel.java) 
                                                                                 at android.os.Parcel.readArrayMapInternal(Parcel.java) 
                                                                                 at android.os.BaseBundle.unparcel(BaseBundle.java) 
                                                                                 at android.os.BaseBundle.getSerializable(BaseBundle.java) 
                                                                                 at android.os.Bundle.getSerializable(Bundle.java) 
                                                                                 at android.content.Intent.getSerializableExtra(Intent.java) 
                                                                                 at com.facebook.zero.k.o.onReceive(:189345) 
                                                                                 at com.facebook.common.init.n.onReceive(:58756) 
                                                                                 at com.facebook.content.w.onReceive(:64476) 
                                                                                 at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java) 
                                                                                 at android.os.Handler.handleCallback(Handler.java) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java) 
                                                                                 at android.os.Looper.loop(Looper.java) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java) 
                                                                              Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.zero.sdk.common.TokenRequestReason" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.facebook.orca-1/base.apk", zip file "/data/app/com.facebook.orca-1/base.apk"],nativeLibraryDirectories=[/data/user/0/com.security.multiple.account.applock/virtual/data/app/com.facebook.orca/lib, /vendor/lib, /system/lib]]
                                                                                 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                 at java.lang.Class.classForName(Native Method) 
                                                                                 at java.lang.Class.forName(Class.java:324) 
                                                                                 at android.os.Parcel$2.resolveClass(Parcel.java) 
                                                                                 at java.io.ObjectInputStream.readEnumDescInternal(ObjectInputStream.java:1551) 
                                                                                 at java.io.ObjectInputStream.readEnumDesc(ObjectInputStream.java:1532) 
                                                                                 at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1577) 
                                                                                 at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:767) 
                                                                                 at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983) 
                                                                                 at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940) 
                                                                                 at android.os.Parcel.readSerializable(Parcel.java) 
                                                                                 at android.os.Parcel.readValue(Parcel.java) 
                                                                                 at android.os.Parcel.readArrayMapInternal(Parcel.java) 
                                                                                 at android.os.BaseBundle.unparcel(BaseBundle.java) 
                                                                                 at android.os.BaseBundle.getSerializable(BaseBundle.java) 
                                                                                 at android.os.Bundle.getSerializable(Bundle.java) 
                                                                                 at android.content.Intent.getSerializableExtra(Intent.java) 
                                                                                 at com.facebook.zero.k.o.onReceive(:189345) 
                                                                                 at com.facebook.common.init.n.onReceive(:58756) 
                                                                                 at com.facebook.content.w.onReceive(:64476) 
                                                                                 at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java) 
                                                                                 at android.os.Handler.handleCallback(Handler.java) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java) 
                                                                                 at android.os.Looper.loop(Looper.java) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java) 
                                                                             	Suppressed: java.lang.ClassNotFoundException: [MultiDexclassLoader prefab]
                                                                                 at com.facebook.common.dextricks.MultiDexClassLoader.<clinit>(:11988)
                                                                                 at com.facebook.common.dextricks.DexStore.loadDexFiles(:11259)
                                                                                 at com.facebook.common.dextricks.DexStore.loadAllImpl(:11193)
                                                                                 at com.facebook.common.dextricks.DexStore.loadAll(:11046)
                                                                                 at com.facebook.common.dextricks.DexLibLoader.loadAllImpl(:10014)
                                                                                 at com.facebook.common.dextricks.DexLibLoader.loadAll(:9981)
                                                                                 at com.facebook.messenger.app.MessengerApplication.b(:16098)
                                                                                 at com.facebook.base.b.b.c(:4137)
                                                                                 at com.facebook.base.b.m.run(:4661)
09-23 17:10:21.401 17605-17605/com.security.multiple.account.applock:p1 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                          Process: com.facebook.orca, PID: 17605
                                                                                          java.lang.RuntimeException: Error receiving broadcast Intent { act=com.facebook.zero.ACTION_ZERO_REFRESH_TOKEN pkg=com.facebook.katana (has extras) } in com.facebook.base.broadcast.d@4fe957
                                                                                              at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java)
                                                                                              at android.os.Handler.handleCallback(Handler.java)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java)
                                                                                              at android.os.Looper.loop(Looper.java)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java)
                                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
                                                                                           Caused by: java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = com.facebook.zero.sdk.common.TokenRequestReason)
                                                                                              at android.os.Parcel.readSerializable(Parcel.java)
                                                                                              at android.os.Parcel.readValue(Parcel.java)
                                                                                              at android.os.Parcel.readArrayMapInternal(Parcel.java)
                                                                                              at android.os.BaseBundle.unparcel(BaseBundle.java)
                                                                                              at android.os.BaseBundle.getSerializable(BaseBundle.java)
                                                                                              at android.os.Bundle.getSerializable(Bundle.java)
                                                                                              at android.content.Intent.getSerializableExtra(Intent.java)
                                                                                              at com.facebook.zero.k.o.onReceive(:189345)
                                                                                              at com.facebook.common.init.n.onReceive(:58756)
                                                                                              at com.facebook.content.w.onReceive(:64476)
                                                                                              at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java) 
                                                                                              at android.os.Handler.handleCallback(Handler.java) 
                                                                                              at android.os.Handler.dispatchMessage(Handler.java) 
                                                                                              at android.os.Looper.loop(Looper.java) 
                                                                                              at android.app.ActivityThread.main(ActivityThread.java) 
                                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java) 
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java) 
                                                                                           Caused by: java.lang.ClassNotFoundException: com.facebook.zero.sdk.common.TokenRequestReason
                                                                                              at java.lang.Class.classForName(Native Method)
                                                                                              at java.lang.Class.forName(Class.java:324)
                                                                                              at android.os.Parcel$2.resolveClass(Parcel.java)
                                                                                              at java.io.ObjectInputStream.readEnumDescInternal(ObjectInputStream.java:1551)
                                                                                              at java.io.ObjectInputStream.readEnumDesc(ObjectInputStream.java:1532)
                                                                                              at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1577)
                                                                                              at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:767)
                                                                                              at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
                                                                                              at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
                                                                                              at android.os.Parcel.readSerializable(Parcel.java) 
                                                                                              at android.os.Parcel.readValue(Parcel.java) 
                                                                                              at android.os.Parcel.readArrayMapInternal(Parcel.java) 
                                                                                              at android.os.BaseBundle.unparcel(BaseBundle.java) 
                                                                                              at android.os.BaseBundle.getSerializable(BaseBundle.java) 
                                                                                              at android.os.Bundle.getSerializable(Bundle.java) 
                                                                                              at android.content.Intent.getSerializableExtra(Intent.java) 
                                                                                              at com.facebook.zero.k.o.onReceive(:189345) 
                                                                                              at com.facebook.common.init.n.onReceive(:58756) 
                                                                                              at com.facebook.content.w.onReceive(:64476) 
                                                                                              at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java) 
                                                                                              at android.os.Handler.handleCallback(Handler.java) 
                                                                                              at android.os.Handler.dispatchMessage(Handler.java) 
                                                                                              at android.os.Looper.loop(Looper.java) 
                                                                                              at android.app.ActivityThread.main(ActivityThread.java) 
                                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java) 
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java) 
                                                                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.zero.sdk.common.TokenRequestReason" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.facebook.orca-1/base.apk", zip file "/data/app/com.facebook.orca-1/base.apk"],nativeLibraryDirectories=[/data/user/0/com.security.multiple.account.applock/virtual/data/app/com.facebook.orca/lib, /vendor/lib, /system/lib]]
                                                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                              at java.lang.Class.classForName(Native Method) 
                                                                                              at java.lang.Class.forName(Class.java:324) 
                                                                                              at android.os.Parcel$2.resolveClass(Parcel.java) 
                                                                                              at java.io.ObjectInputStream.readEnumDescInternal(ObjectInputStream.java:1551) 
                                                                                              at java.io.ObjectInputStream.readEnumDesc(ObjectInputStream.java:1532) 
                                                                                              at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1577) 
                                                                                              at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:767) 
                                                                                              at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983) 
                                                                                              at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940) 
                                                                                              at android.os.Parcel.readSerializable(Parcel.java) 
                                                                                              at android.os.Parcel.readValue(Parcel.java) 
                                                                                              at android.os.Parcel.readArrayMapInternal(Parcel.java) 
                                                                                              at android.os.BaseBundle.unparcel(BaseBundle.java) 
                                                                                              at android.os.BaseBundle.getSerializable(BaseBundle.java) 
                                                                                              at android.os.Bundle.getSerializable(Bundle.java) 
                                                                                              at android.content.Intent.getSerializableExtra(Intent.java) 
                                                                                              at com.facebook.zero.k.o.onReceive(:189345) 
                                                                                              at com.facebook.common.init.n.onReceive(:58756) 
                                                                                              at com.facebook.content.w.onReceive(:64476) 
                                                                                              at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java) 
                                                                                              at android.os.Handler.handleCallback(Handler.java) 
                                                                                              at android.os.Handler.dispatchMessage(Handler.java) 
                                                                                              at android.os.Looper.loop(Looper.java) 
                                                                                              at android.app.ActivityThread.main(ActivityThread.java) 
                                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java) 
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java) 
                                                                                          	Suppressed: java.lang.ClassNotFoundException: [MultiDexclassLoader prefab]
                                                                                              at com.facebook.common.dextricks.MultiDexClassLoader.<clinit>(:11988)
                                                                                              at com.facebook.common.dextricks.DexStore.loadDexFiles(:11259)
                                                                                              at com.facebook.common.dextricks.DexStore.loadAllImpl(:11193)
                                                                                              at com.facebook.common.dextricks.DexStore.loadAll(:11046)
                                                                                              at com.facebook.common.dextricks.DexLibLoader.loadAllImpl(:10014)
                                                                                              at com.facebook.common.dextricks.DexLibLoader.loadAll(:9981)
                                                                                              at com.facebook.messenger.app.MessengerApplication.b(:16098)
                                                                                              at com.facebook.base.b.b.c(:4137)
                                                                                              at com.facebook.base.b.m.run(:4661)
