### ISSUE TITLE
在Facebook中打开 Instagram 闪退

### ISSUE THREAD

**Issue by renqingyou** [asLody/VirtualApp#126]
在Facebook中打开 Instagram 闪退，之前是报错, 使用Facebook遇到好些问题！

**Comment by asLody** [comment]
Give me the detail.

**Comment by renqingyou** [comment]
打开facebook,切换到设置选项卡，在活动的下面一栏有个Instagram 选项，点击Instagram ，闪退

**Comment by piersguo** [comment]
请问你这边facebook双开后能登录吗，我这边一登录就闪退，不知为啥

**Comment by jawadhussainmughal** [comment]
Facebook not running even not lunch login screen.
Gives SecurityException. 


virtualapp:p1 E/uncaught: java.lang.SecurityException: Unknown calling package name 'com.facebook.katana'.
                                                                at android.os.Parcel.readException(Parcel.java:1465)
                                                                at android.os.Parcel.readException(Parcel.java:1419)
                                                                at X.516.a()
                                                                at X.50W.a()
                                                                at X.52R.a()
                                                                at X.52P.run()
                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                at X.53W.run()
                                                                at java.lang.Thread.run(Thread.java:841)
