### ISSUE TITLE
登陆facebook，弹出停止运行

### ISSUE THREAD

**Issue by renqingyou** [asLody/VirtualApp#132]

**Comment by renqingyou** [comment]
09-30 14:18:38.315 791-1144/? E/Parcel: Class not found when unmarshalling: io.virtualapp.home.models.AppModel, e: java.lang.ClassNotFoundException: io.virtualapp.home.models.AppModel
09-30 14:18:38.345 11258-11258/io.virtualapp E/NavigationBar: meta-data ==> set Navi Bg (package:io.virtualapp, portResource ID:0, landResource ID:0, alpha:0)
09-30 14:18:38.455 296-422/? E/ThermalEngine: [GPU_MON] 0 percent. Current Sampling Time is 4 sec 
09-30 14:18:39.135 8497-11274/? E/a: java.lang.NullPointerException
09-30 14:18:39.495 11946-11946/io.virtualapp:p0 E/NavigationBar: meta-data ==> set Navi Bg (package:com.facebook.katana, portResource ID:0, landResource ID:0, alpha:0)
09-30 14:18:56.835 11946-12337/io.virtualapp:p0 E/fb4a(:<default>):MqttService: Unexpected UID 10002 11946 10121 11946 com.facebook.katana
09-30 14:18:56.845 11946-12337/io.virtualapp:p0 E/ACRA: ACRA caught a SecurityException exception for com.facebook.katana. Building report.
09-30 14:18:56.845 11946-12337/io.virtualapp:p0 E/fb4a(:<default>):ACRA: Handling exception for crash
                                                                         java.lang.SecurityException: Unexpected UID 10002 11946 10121 11946 com.facebook.katana
                                                                             at X$zY.g(:344111)
                                                                             at X$zY.a(:344123)
                                                                             at com.facebook.push.mqtt.service.MqttPushServiceManager.r(:379307)
                                                                             at X$Dw.run(:381697)
                                                                             at android.os.Handler.handleCallback(Handler.java:725)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                             at android.os.Looper.loop(Looper.java:137)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:60)
09-30 14:18:58.465 296-422/? E/ThermalEngine: [GPU_MON] 1 percent. Current Sampling Time is 4 sec 
09-30 14:18:58.515 11946-12337/io.virtualapp:p0 E/MediaCodecList: brunchMediaCodecListEx != NULL
09-30 14:18:58.515 11946-12337/io.virtualapp:p0 E/MediaCodecList: getNewMediaCodecItem [0][DTSDecode][audio/dts]
09-30 14:18:58.515 11946-12337/io.virtualapp:p0 E/MediaCodecList: getNewMediaCodecItem [0][DDPDecode][audio/eac3]
09-30 14:18:58.515 11946-12337/io.virtualapp:p0 E/MediaCodecList: getNewMediaCodecItem [0][DDPDecode][audio/ac3]
09-30 14:18:58.515 11946-12337/io.virtualapp:p0 E/MediaCodecList: getNewMediaCodecItem [0][OMX.VisualOn.Video.Decoder.XXX][video/hevc]
09-30 14:18:58.515 283-4855/? E/OMX-VDEC-1080P: In OMX vdec Constructor
09-30 14:18:58.515 283-4855/? E/OMX-VDEC-1080P: vidc.dec.debug.ts value is 0
09-30 14:18:58.515 283-4855/? E/OMX-VDEC-1080P: vidc.dec.debug.concealedmb value is 0
09-30 14:18:58.515 283-4855/? E/OMX-VDEC-1080P: vidc.dec.debug.extradata value is 0
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P:  omx_vdec::component_init(): Open returned fd 34, errno 22
09-30 14:18:58.595 283-12680/? E/OMX-VDEC-1080P: omx_vdec: Async thread start
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P: Capabilities: driver_name = msm_vidc_driver, card = msm_vdec_8974, bus_info = , version = 1, capabilities = 4003000
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P: fmt: description: Y/CbCr 4:2:0, fmt: 3231564e, flags = 0
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P: fmt: description: Mpeg4 compressed format, fmt: 3447504d, flags = 1
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P: fmt: description: Mpeg2 compressed format, fmt: 3247504d, flags = 1
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P: fmt: description: H263 compressed format, fmt: 33363248, flags = 1
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P: fmt: description: VC-1 compressed format, fmt: 47314356, flags = 1
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P: fmt: description: VC-1 compressed format G, fmt: 4c314356, flags = 1
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P: fmt: description: H264 compressed format, fmt: 34363248, flags = 1
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P: fmt: description: HEVC compressed format, fmt: 43564548, flags = 1
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P: fmt: description: VP8 compressed format, fmt: 30385056, flags = 1
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P: fmt: description: DIVX 311 compressed format, fmt: 33564944, flags = 1
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P: fmt: description: DIVX 4/5/6 compressed format, fmt: 58564944, flags = 1
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P: NOTE_CIF: W/H 320 (0), 240 (0)
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P:  Set Format was successful 
                                                 
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P:  Set Format was successful 
                                                 
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P: NOTE: enable_extradata: actual[0] requested[131072] enable[1], is_internal: 1
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P: Count = 4 
                                                 
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P: Buffer Size = 6291456 
                                                 
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P:  video session supported
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P: Input Buffer Size =6291456 
                                                 
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P: Count = 18 
                                                 
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P: Buffer Size = 147584 
                                                 
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P:  video session supported
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P:  No color conversion required
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P:  omx_vdec::component_init() success
09-30 14:18:58.595 283-283/? E/OMX-VDEC-1080P: returning 2141391876
09-30 14:18:58.595 283-844/? E/OMX-VDEC-1080P: returning 19
09-30 14:18:58.595 283-4855/? E/OMX-VDEC-1080P: returning 19
09-30 14:18:58.595 283-12681/? E/OMX-VDEC-1080P: omx_vdec: message thread start
09-30 14:18:58.595 283-924/? E/OMX-VDEC-1080P:  Playback Ended - PASSED
09-30 14:18:58.595 283-924/? E/OMX-VDEC-1080P:  ALL output buffers are freed/released
09-30 14:18:58.595 283-924/? E/OMX-VDEC-1080P:  Close the driver instance
09-30 14:18:58.595 283-924/? E/OMX-VDEC-1080P:  omx_vdec::component_deinit() complete
09-30 14:18:58.595 283-924/? E/OMX-VDEC-1080P: In OMX vdec Destructor
09-30 14:18:58.595 283-924/? E/OMX-VDEC-1080P: Waiting on OMX Msg Thread exit
09-30 14:18:58.605 283-12681/? E/OMX-VDEC-1080P: ERROR: read from pipe failed, ret -1 errno 9
09-30 14:18:58.605 283-12681/? E/OMX-VDEC-1080P: omx_vdec: message thread stop
09-30 14:18:58.605 283-924/? E/OMX-VDEC-1080P: Waiting on OMX Async Thread exit
09-30 14:18:58.605 283-12680/? E/OMX-VDEC-1080P:  VIDC Close Done Recieved and async_message_thread Exited 
09-30 14:18:58.605 283-12680/? E/OMX-VDEC-1080P: omx_vdec: Async thread stop
09-30 14:18:58.605 283-924/? E/OMX-VDEC-1080P: Exit OMX vdec Destructor
                                               
                                               [ 09-30 14:18:58.605   283:  924 E/         ]
                                               
                                                Destroy C2D instance
                                               
                                               [ 09-30 14:18:58.605   283:  924 E/         ]
                                               
                                                Destroy C2D instance
09-30 14:18:59.935 11946-12209/io.virtualapp:p0 E/fb4a(:<default>):MqttService: Unexpected UID 10002 11946 10121 11946 com.facebook.katana
09-30 14:19:00.515 11946-12337/io.virtualapp:p0 E/AppStateLoggerExceptionHandler: Handing uncaught exception
                                                                                  java.lang.SecurityException: Unexpected UID 10002 11946 10121 11946 com.facebook.katana
                                                                                      at X$zY.g(:344111)
                                                                                      at X$zY.a(:344123)
                                                                                      at com.facebook.push.mqtt.service.MqttPushServiceManager.r(:379307)
                                                                                      at X$Dw.run(:381697)
                                                                                      at android.os.Handler.handleCallback(Handler.java:725)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                                      at android.os.Looper.loop(Looper.java:137)
                                                                                      at android.os.HandlerThread.run(HandlerThread.java:60)
09-30 14:19:00.525 11946-12337/io.virtualapp:p0 E/CatchMeIfYouCan: Uncaught exception in '<default>':
09-30 14:19:00.525 11946-12337/io.virtualapp:p0 E/CatchMeIfYouCan: java.lang.SecurityException: Unexpected UID 10002 11946 10121 11946 com.facebook.katana
09-30 14:19:00.525 11946-12337/io.virtualapp:p0 E/CatchMeIfYouCan:     at X$zY.g(:344111)
09-30 14:19:00.525 11946-12337/io.virtualapp:p0 E/CatchMeIfYouCan:     at X$zY.a(:344123)
09-30 14:19:00.525 11946-12337/io.virtualapp:p0 E/CatchMeIfYouCan:     at com.facebook.push.mqtt.service.MqttPushServiceManager.r(:379307)
09-30 14:19:00.525 11946-12337/io.virtualapp:p0 E/CatchMeIfYouCan:     at X$Dw.run(:381697)
09-30 14:19:00.525 11946-12337/io.virtualapp:p0 E/CatchMeIfYouCan:     at android.os.Handler.handleCallback(Handler.java:725)
09-30 14:19:00.525 11946-12337/io.virtualapp:p0 E/CatchMeIfYouCan:     at android.os.Handler.dispatchMessage(Handler.java:92)
09-30 14:19:00.525 11946-12337/io.virtualapp:p0 E/CatchMeIfYouCan:     at android.os.Looper.loop(Looper.java:137)
09-30 14:19:00.525 11946-12337/io.virtualapp:p0 E/CatchMeIfYouCan:     at android.os.HandlerThread.run(HandlerThread.java:60)
09-30 14:19:00.525 11946-12337/io.virtualapp:p0 E/AndroidRuntime: FATAL EXCEPTION: MqttHandler
                                                                  java.lang.SecurityException: Unexpected UID 10002 11946 10121 11946 com.facebook.katana
                                                                      at X$zY.g(:344111)
                                                                      at X$zY.a(:344123)
                                                                      at com.facebook.push.mqtt.service.MqttPushServiceManager.r(:379307)
                                                                      at X$Dw.run(:381697)
                                                                      at android.os.Handler.handleCallback(Handler.java:725)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                      at android.os.Looper.loop(Looper.java:137)
                                                                      at android.os.HandlerThread.run(HandlerThread.java:60)
09-30 14:19:00.595 11258-11258/io.virtualapp E/NavigationBar: meta-data ==> set Navi Bg (package:io.virtualapp, portResource ID:0, landResource ID:0, alpha:0)
09-30 14:19:02.065 11946-12326/io.virtualapp:p0 E/ActivityThread: Failed to find provider info for com.facebook.appmanager.attribution
09-30 14:19:04.495 11946-12746/io.virtualapp:p0 E/fb4a(:<default>):GRAPHQL_QUERY_STRING: Trying to set unknown parameter '0' on query 'ComposerOrderQueryFragment'
09-30 14:19:04.495 11946-12746/io.virtualapp:p0 E/fb4a(:<default>):GRAPHQL_QUERY_STRING: Trying to set unknown parameter '1' on query 'ComposerOrderQueryFragment'
09-30 14:19:05.815 11946-12723/io.virtualapp:p0 E/fb4a(:<default>):GRAPHQL_QUERY_STRING: Trying to set unknown parameter '0' on query 'ComposerOrderQueryFragment'
09-30 14:19:05.815 11946-12723/io.virtualapp:p0 E/fb4a(:<default>):GRAPHQL_QUERY_STRING: Trying to set unknown parameter '1' on query 'ComposerOrderQueryFragment'
09-30 14:19:13.395 10592-10592/? E/NetworkScheduler: Unable to resolve correct action against com.facebook.katana/com.google.android.gms.gcm.gmsproc.GcmInGmsTaskService to instantiate callback. not executing task.
09-30 14:19:18.465 296-422/? E/ThermalEngine: [GPU_MON] 0 percent. Current Sampling Time is 4 sec
