### ISSUE TITLE
请教IOHook在JNI_OnLoad时候经常返回错误，无法加载lib

### ISSUE THREAD

**Issue by piersguo** [asLody/VirtualApp#133]
Lody, 

请教下在启动双开应用时，从log中经常看到如下加载iohook lib出错的log，大部分双开应用都失败在env->RegisterNatives部分，请问这部分出错了如何修正，有什么不良影响吗，不是很理解这块。
E/VxxIOHook: java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/io.virtualapp/lib/arm/libiohook.so"
                                                at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                at java.lang.System.loadLibrary(System.java:1076)
                                                at com.lody.virtual.IOHook.<clinit>(IOHook.java:47)
                                                at com.lody.virtual.client.hook.patchs.libcore.GetUid.afterCall(GetUid.java:21)
                                                at com.lody.virtual.client.hook.base.HookDelegate$HookHandler.invoke(HookDelegate.java:160)
                                                at java.lang.reflect.Proxy.invoke(Proxy.java:393)
                                                at $Proxy2.getuid(Unknown Source)
                                                at android.system.Os.getuid(Os.java:216)
                                                at android.os.Process.myUid(Process.java:791)
                                                at android.content.ContentProvider.attachInfo(ContentProvider.java:1739)
                                                at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
                                                at android.app.ActivityThread.installProvider(ActivityThread.java:5267)
                                                at android.app.ActivityThread.installContentProviders(ActivityThread.java:4862)
                                                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4802)
                                                at android.app.ActivityThread.access$1600(ActivityThread.java:157)
                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                at android.os.Looper.loop(Looper.java:148)
                                                at android.app.ActivityThread.main(ActivityThread.java:5551)
                                                at java.lang.reflect.Method.invoke(Native Method)
                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

**Comment by renqingyou** [comment]
经常会出现这种问题，现在问题还是比较多的
