### ISSUE TITLE
在华为手机上(Android5.0+)会因注册过多Receiver而崩溃

### ISSUE THREAD

**Issue by cddjr** [asLody/VirtualApp#149]
http://stackoverflow.com/questions/35220416/java-lang-illegalargumentexception-register-too-many-broadcast-receivers

http://bbs.csdn.net/topics/392006408

Log如下
```
io.virtualapp:x E/LoadedApk: io.virtualapp registered 501 Receivers  in 1 Contexts
java.lang.Throwable
at android.app.LoadedApk.checkRecevierRegisteredLeakLocked(LoadedApk.java:770)
at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:800)
at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1329)
at android.app.ContextImpl.registerReceiver(ContextImpl.java:1309)
at com.lody.virtual.server.am.StaticBroadcastSystem.startApp(StaticBroadcastSystem.java:59)
at com.lody.virtual.server.pm.VAppManagerService.install(VAppManagerService.java:190)
at com.lody.virtual.server.pm.VAppManagerService.preloadAllApps(VAppManagerService.java:95)
at com.lody.virtual.server.pm.VAppManagerService.systemReady(VAppManagerService.java:70)
```

产生原因是VA把所有插件中声明的静态Receiver都转为动态注册在:x进程中, 一旦插件数量增加或者装了gms后，极易超过华为的限制(一个进程最多动态注册500个Receiver)

目前临时方案是所有registerReceiver的调用都忽略这个异常
```
try {
    mContext.registerReceiver(r, cloneFilter, null, mScheduler);
} catch (Throwable e) {
}
```

但有没有更好的方式呢？ 比如把StaticBroadcastReceiver放入每个插件进程中去单独运行，而不要都由:x进程处理。

**Comment by asLody** [comment]
但是，正常情况下，一个进程不应该会注册那么多的Receiver啊，
一个进程注册的Receiver数 = 静态Receiver数 + 动态Receiver数 + 1
