### ISSUE TITLE
Fcebook

### ISSUE THREAD

**Issue by cloud20161002** [asLody/VirtualApp#158]

**Comment by cqllang** [comment]
我的nexus 6p也是 启动报如下错误:

-28 19:00:08.983 18645-18700/? E/00E: Uncaught exception in '<default>':
11-28 19:00:08.983 18645-18700/? E/00E: java.lang.ExceptionInInitializerError
11-28 19:00:08.983 18645-18700/? E/00E:     at com.facebook.common.dextricks.DalvikInternals.setJvmStreamEnabled(:2042)
11-28 19:00:08.983 18645-18700/? E/00E:     at com.facebook.katana.app.FacebookApplication.b(:213)
11-28 19:00:08.983 18645-18700/? E/00E:     at com.facebook.katana.app.FacebookApplication.b(:249)
11-28 19:00:08.983 18645-18700/? E/00E:     at X.001.c(:713)
11-28 19:00:08.983 18645-18700/? E/00E:     at com.facebook.base.app.SplashScreenApplication$1.run(:6116)
11-28 19:00:08.983 18645-18700/? E/00E: Caused by: java.lang.RuntimeException: dlopen("libart.so"): dlopen failed: library "libart.so" not found
11-28 19:00:08.983 18645-18700/? E/00E:     at com.facebook.common.dextricks.DalvikInternals.integrateWithLibSigChain(Native Method)
11-28 19:00:08.983 18645-18700/? E/00E:     at com.facebook.common.dextricks.DalvikInternals.<clinit>(:2054)
11-28 19:00:08.983 18645-18700/? E/00E: 	... 5 more
11-28 19:00:08.984 18645-18700/? E/AndroidRuntime: FATAL EXCEPTION: EnsureDelegate
                                                   Process: com.facebook.katana, PID: 18645
                                                   java.lang.ExceptionInInitializerError
                                                       at com.facebook.common.dextricks.DalvikInternals.setJvmStreamEnabled(:2042)
                                                       at com.facebook.katana.app.FacebookApplication.b(:213)
                                                       at com.facebook.katana.app.FacebookApplication.b(:249)
                                                       at X.001.c(:713)
                                                       at com.facebook.base.app.SplashScreenApplication$1.run(:6116)
                                                    Caused by: java.lang.RuntimeException: dlopen("libart.so"): dlopen failed: library "libart.so" not found
                                                       at com.facebook.common.dextricks.DalvikInternals.integrateWithLibSigChain(Native Method)
                                                       at com.facebook.common.dextricks.DalvikInternals.<clinit>(:2054)
                                                       at com.facebook.common.dextricks.DalvikInternals.setJvmStreamEnabled(:2042) 
                                                       at com.facebook.katana.app.FacebookApplication.b(:213) 
                                                       at com.facebook.katana.app.FacebookApplication.b(:249) 
                                                       at X.001.c(:713) 
                                                       at com.facebook.base.app.SplashScreenApplication$1.run(:6116)

**Comment by renqingyou** [comment]
应该是还没适配7.0系统

**Comment by cloud20161002** [comment]
有人解决了这个问题么？看了几天还是没解决，问题应该是一个service找不到，但是hook中并没有service相关的调用，facebook的代码反编译不全，看不到抛异常的代码：
java.lang.IllegalStateException: Unable to find the UploadService!
W/System.err:     at X.2Cp.b(:383271)
W/System.err:     at X.2Cp.b(:383259)
W/System.err:     at X.0q7.b(:147086)
W/System.err:     at X.0q7.b(:147114)
W/System.err:     at X.0q7.handleMessage(:147031)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:154)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by renqingyou** [comment]
感觉这个应用目前对国外的一些即时通信软件还有不少问题！
我之前也用过一段时间facebook，发现问题不少！
