### ISSUE TITLE
华为手机总是出现Register too many Broadcast Receivers

### ISSUE THREAD

**Issue by JOKERCHAN** [asLody/VirtualApp#171]
java.lang.AssertionError: Register too many Broadcast Receivers
                                                                       at android.app.LoadedApk.checkRecevierRegisteredLeakLocked(LoadedApk.java:772)
                                                                       at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:800)
                                                                       at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1329)
                                                                       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1309)
                                                                       at com.lody.virtual.server.am.StaticBroadcastSystem.startApp(StaticBroadcastSystem.java:54)
                                                                       at com.lody.virtual.server.pm.VAppManagerService.install(VAppManagerService.java:193)
                                                                       at com.lody.virtual.server.pm.VAppManagerService.preloadAllApps(VAppManagerService.java:98)
                                                                       at com.lody.virtual.server.pm.VAppManagerService.systemReady(VAppManagerService.java:70)
                                                                       at com.lody.virtual.server.BinderProvider.onCreate(BinderProvider.java:42)
                                                                       at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)
                                                                       at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
                                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:5247)
                                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:4836)
                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4767)
                                                                       at android.app.ActivityThread.access$1600(ActivityThread.java:165)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:150)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by cddjr** [comment]
这个我提过了 详见 #149

**Comment by JOKERCHAN** [comment]
如果那样做 会不会出现问题呢 。运行时间过长会不会crash
