### ISSUE TITLE
最近版本运行插件黑屏，卡死，之前的版本没这个问题

### ISSUE THREAD

**Issue by cocosjiang** [asLody/VirtualApp#195]
最近的版本 运行有动态库so的插件  直接回调onKillProgress 然后黑屏  之前的版本都是好好的
io.virtualapp:p0 E/IOHook: killProcess: pid = 15480, signal = 18.
02-01 13:06:12.496 15480-15480/? E/IOHook: killProcess: pid = 15480, signal = 9.
02-01 13:06:12.496 15480-15480/? E/IOHook: java.lang.Throwable
                                               at com.lody.virtual.IOHook.onKillProcess(IOHook.java:114)
                                               at java.lang.Runtime.nativeLoad(Native Method)
                                               at java.lang.Runtime.loadLibrary(Runtime.java:369)

**Comment by asLody** [comment]
最新VA的so配置已经更改过了：
ndkBuild {
                abiFilters "armeabi", "armeabi-v7a", "x86"
            }
之前的版本是：
ndkBuild {
                abiFilters "armeabi", "x86"
            }

**Comment by cocosjiang** [comment]
armeabi-v7a我已经去掉了 而且还是运行在32位机器上

**Comment by asLody** [comment]
请先确定demo能否运行，demo能运行则是你的个人问题。

**Comment by cocosjiang** [comment]
就是在demo上直接选取插件运行的
