### ISSUE TITLE
startActivityForResult没有被Hook

### ISSUE THREAD

**Issue by codehz** [asLody/VirtualApp#198]
这导致部分应用的闪退无法轻易解决
```
02-04 21:15:28.391 4778-4795/jp.main.brits.android.filer.app D/VA-Native: do_dlopen : /vendor/lib/egl/libEGL_adreno.so, return : 0xf70e4550.
02-04 21:15:28.391 4778-4795/jp.main.brits.android.filer.app I/OpenGLRenderer: Initialized EGL, version 1.4
02-04 21:15:28.391 4778-4795/jp.main.brits.android.filer.app D/OpenGLRenderer: Swap behavior 1
02-04 21:15:28.467 4778-4795/jp.main.brits.android.filer.app D/VA-Native: do_dlopen : /system/lib/hw/gralloc.msm8996.so, return : 0xf70e61d0.
02-04 21:15:33.965 4778-4785/jp.main.brits.android.filer.app W/art: Suspending all threads took: 23.778ms
02-04 21:15:34.726 4778-4778/jp.main.brits.android.filer.app D/AndroidRuntime: Shutting down VM
02-04 21:15:34.728 4778-4778/jp.main.brits.android.filer.app E/uncaught: android.os.FileUriExposedException: file:///storage/emulated/0/newsreader_news_wxkm.apk exposed beyond app through Intent.getData()
                                                                             at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
                                                                             at android.net.Uri.checkFileUriExposed(Uri.java:2346)
                                                                             at android.content.Intent.prepareToLeaveProcess(Intent.java:8996)
                                                                             at android.content.Intent.prepareToLeaveProcess(Intent.java:8957)
                                                                             at android.app.Instrumentation.execStartActivity(Instrumentation.java:1519)
                                                                             at android.app.Activity.startActivityForResult(Activity.java:4225)
                                                                             at android.app.Activity.startActivityForResult(Activity.java:4183)
                                                                             at jp.main.brits.android.filer.FileListActivity.b(Unknown Source)
                                                                             at jp.main.brits.android.filer.FileListActivity.a(Unknown Source)
                                                                             at jp.main.brits.android.filer.FileListActivity.a(Unknown Source)
                                                                             at jp.main.brits.android.filer.ui.c.a.b(Unknown Source)
                                                                             at jp.main.brits.android.filer.ui.c.a.onItemClick(Unknown Source)
                                                                             at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                                                                             at android.widget.AbsListView.performItemClick(AbsListView.java:1203)
                                                                             at android.widget.AbsListView$PerformClick.run(AbsListView.java:3294)
                                                                             at android.widget.AbsListView$4.run(AbsListView.java:4217)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
02-04 21:15:34.728 4778-4778/jp.main.brits.android.filer.app W/System.err: java.lang.Exception
02-04 21:15:34.732 4778-4778/jp.main.brits.android.filer.app W/System.err:     at com.lody.virtual.client.VClientImpl$3.start(VClientImpl.java:215)
02-04 21:15:34.732 4778-4778/jp.main.brits.android.filer.app W/System.err:     at java.lang.Runtime.exit(Runtime.java:153)
02-04 21:15:34.732 4778-4778/jp.main.brits.android.filer.app W/System.err:     at java.lang.System.exit(System.java:1384)
02-04 21:15:34.732 4778-4778/jp.main.brits.android.filer.app W/System.err:     at com.lody.virtual.client.VClientImpl$RootThreadGroup.uncaughtException(VClientImpl.java:533)
02-04 21:15:34.733 4778-4778/jp.main.brits.android.filer.app W/System.err:     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
```
另外为什么有时候虚拟化的app的进程名是:p0什么的，有时候就是它自己的包名，调试起来一点都不方便。。。

**Comment by codehz** [comment]
尝试解决这个问题发现并不需要hook startActivityForResult
