### ISSUE TITLE
（android 7.1.1 custom rom）含有WebView的Activity闪退

### ISSUE THREAD

**Issue by codehz** [asLody/VirtualApp#200]
```
02-05 10:10:15.815 21989-22037/io.virtualapp:p1 E/cr_ChildProcessConnect: Could not retrieve info about service ComponentInfo{com.android.webview/org.chromium.content.app.SandboxedProcessService0}
                                                                                 android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{com.android.webview/org.chromium.content.app.SandboxedProcessService0}
                                                                                     at android.app.ApplicationPackageManager.getServiceInfo(ApplicationPackageManager.java:415)
                                                                                     at org.chromium.content.browser.ChildProcessConnectionImpl.isExportedService(ChildProcessConnectionImpl.java:252)
                                                                                     at org.chromium.content.browser.ChildProcessConnectionImpl.<init>(ChildProcessConnectionImpl.java:231)
                                                                                     at org.chromium.content.browser.ChildProcessLauncher$ChildConnectionAllocator.allocate(ChildProcessLauncher.java:93)
                                                                                     at org.chromium.content.browser.ChildProcessLauncher.allocateConnection(ChildProcessLauncher.java:381)
                                                                                     at org.chromium.content.browser.ChildProcessLauncher.allocateBoundConnection(ChildProcessLauncher.java:419)
                                                                                     at org.chromium.content.browser.ChildProcessLauncher.warmUp(ChildProcessLauncher.java:652)
                                                                                     at org.chromium.android_webview.AwBrowserProcess$1$1.run(AwBrowserProcess.java:92)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                     at java.lang.Thread.run(Thread.java:761)
02-05 10:10:15.819 21989-22037/io.virtualapp:p1 E/uncaught: java.lang.SecurityException: BIND_EXTERNAL_SERVICE required for ComponentInfo{com.android.webview/org.chromium.content.app.SandboxedProcessService0}
                                                                       at android.os.Parcel.readException(Parcel.java:1684)
                                                                       at android.os.Parcel.readException(Parcel.java:1637)
                                                                       at android.app.ActivityManagerProxy.bindService(ActivityManagerNative.java:4404)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.lody.virtual.client.hook.patchs.am.BindService.call(BindService.java:53)
                                                                       at com.lody.virtual.client.hook.base.HookDelegate$HookHandler.invoke(HookDelegate.java:150)
                                                                       at java.lang.reflect.Proxy.invoke(Proxy.java:813)
                                                                       at $Proxy4.bindService(Unknown Source)
                                                                       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1463)
                                                                       at android.app.ContextImpl.bindService(ContextImpl.java:1422)
                                                                       at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
                                                                       at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
                                                                       at org.chromium.content.browser.ChildProcessConnectionImpl$ChildServiceConnection.bind(ChildProcessConnectionImpl.java:141)
                                                                       at org.chromium.content.browser.ChildProcessConnectionImpl.start(ChildProcessConnectionImpl.java:300)
                                                                       at org.chromium.content.browser.ChildProcessLauncher.allocateBoundConnection(ChildProcessLauncher.java:422)
                                                                       at org.chromium.content.browser.ChildProcessLauncher.warmUp(ChildProcessLauncher.java:652)
                                                                       at org.chromium.android_webview.AwBrowserProcess$1$1.run(AwBrowserProcess.java:92)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                       at java.lang.Thread.run(Thread.java:761)
```
推测是部分Rom将系统webview替换成chromium实现，然后在VA里并不存在对应的包。
但是即便将对应的webview安装到VA中，依旧会出现相同的错误.

**Comment by codehz** [comment]
我尝试让系统强制使用Chrome对应的webview，并且在VA中安装Chrome，则出现如下异常:
```
E/WebViewFactory: Chromium WebView package does not exist
                                                                       android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to verify WebView provider, signature mismatch
                                                                           at android.webkit.WebViewFactory.verifyPackageInfo(WebViewFactory.java:252)
                                                                           at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:303)
                                                                           at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:330)
                                                                           at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
                                                                           at android.webkit.WebView.getFactory(WebView.java:2325)
                                                                           at android.webkit.WebView.ensureProviderCreated(WebView.java:2320)
                                                                           at android.webkit.WebView.setOverScrollMode(WebView.java:2379)
                                                                           at android.view.View.<init>(View.java:4023)
                                                                           at android.view.View.<init>(View.java:4146)
                                                                           at android.view.ViewGroup.<init>(ViewGroup.java:579)
                                                                           at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
                                                                           at android.webkit.WebView.<init>(WebView.java:627)
                                                                           at android.webkit.WebView.<init>(WebView.java:572)
                                                                           at android.webkit.WebView.<init>(WebView.java:555)
                                                                           at android.webkit.WebView.<init>(WebView.java:542)
                                                                           at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                           at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                           at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
                                                                           at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                           at android.databinding.e.a(DataBindingUtil.java:116)
                                                                           at android.databinding.e.a(DataBindingUtil.java:88)
                                                                           at com.coolapk.market.view.webview.WebViewFragment.onCreateView(WebViewFragment.java:77)
                                                                           at android.app.Fragment.performCreateView(Fragment.java:2353)
                                                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
                                                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
                                                                           at android.app.BackStackRecord.run(BackStackRecord.java:816)
                                                                           at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
                                                                           at android.app.FragmentController.execPendingActions(FragmentController.java:371)
                                                                           at android.app.Activity.performStart(Activity.java:6695)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2628)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
似乎是验证了签名，但是没有匹配上。。。

**Comment by codehz** [comment]
当我尝试使用Google WebView作为提供者的时候，出现了这个异常：
```
E/uncaught: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.coolapk.market/com.coolapk.market.view.webview.LoginActivity}: android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class android.webkit.WebView
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                  Caused by: android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class android.webkit.WebView
                                                                  Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class android.webkit.WebView
                                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                                     at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                     at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
                                                                     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                     at android.databinding.e.a(DataBindingUtil.java:116)
                                                                     at android.databinding.e.a(DataBindingUtil.java:88)
                                                                     at com.coolapk.market.view.webview.WebViewFragment.onCreateView(WebViewFragment.java:77)
                                                                     at android.app.Fragment.performCreateView(Fragment.java:2353)
                                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
                                                                     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
                                                                     at android.app.BackStackRecord.run(BackStackRecord.java:816)
                                                                     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
                                                                     at android.app.FragmentController.execPendingActions(FragmentController.java:371)
                                                                     at android.app.Activity.performStart(Activity.java:6695)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2628)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                  Caused by: java.lang.IllegalArgumentException: Unsupported ABI: null
                                                                     at dalvik.system.VMRuntime.getInstructionSet(VMRuntime.java:370)
                                                                     at dalvik.system.VMRuntime.is64BitAbi(VMRuntime.java:383)
                                                                     at android.webkit.WebViewFactory.getWebViewNativeLibraryPaths(WebViewFactory.java:505)
                                                                     at android.webkit.WebViewFactory.loadNativeLibrary(WebViewFactory.java:630)
                                                                     at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:344)
                                                                     at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
                                                                     at android.webkit.WebView.getFactory(WebView.java:2325)
                                                                 	at
```
似乎是获取ABI的过程出了问题，考虑到VA中好多hook都是直接return null的，估计可以作为一种解决方案

**Comment by codehz** [comment]
测试：VA中所有包的applicationInfo.primaryCpuAbi结果均为null这是导致使用google webview失败的原因

**Comment by asLody** [comment]
在7.0和7.1.1上均未复现以上crash，但是根据你的Log，我给出了修复方案，你来测试一下。
另：这是什么ROM？

**Comment by codehz** [comment]
应用了这个修改之后，如果选择AOSP Webview将不会出现问题，但是，如果在开发者工具中选择Google WebView或者Chrome Stable依旧会出现崩溃的问题，异常原因是：
```
Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
                                                 at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:371)
                                                 at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
                                                 at android.webkit.WebView.getFactory(WebView.java:2325)
                                                 at android.webkit.WebView.ensureProviderCreated(WebView.java:2320)
                                                 at android.webkit.WebView.setOverScrollMode(WebView.java:2379)
                                             	a
```
通过调试断点可知，GetServiceInfo的hook在这两者情况下我完全没有被使用。

ROM是RR(http://www.resurrectionremix.com/)，其中在开发者工具中可以选择默认webview实现。
其他rom也有部分可以加载WebViewGoogle作为默认webview实现的。。。（而且这个加载是隐式的，只要安装了WebViewGoogle或者Chrome就会使用）

**Comment by codehz** [comment]
但是在我的测试中，如果将 #201 提到的这个primaryCpuApi强制指定后，即可通过将WebViewGoogle安装到容器内来解决默认webview实现设置为WebViewGoogle时的崩溃问题（Chrome还是不行，似乎是验证了签名）

**Comment by codehz** [comment]
上面那个提交成功的解决了WebViewGoogle的问题，经检查，应用内使用的WebView为正确的WebView实现，Chrome Stable作为实现是仍然失败，检查代码发现是硬编码了com.google.android.webview包名，将Chrome的包名加入后居然成功了（没有出现签名校验的问题）。
我认为这里不应该使用这样的硬编码方式，更加合理的方式是通过代码获取WebView包名/或者有一个更加通用的解决方案（比如说弄一个添加例外包名的API）

**Comment by fishjam** [comment]
> 通过调试断点可知，GetServiceInfo的hook在这两者情况下完全没有被使用。

@codehz @asLody ,
各位大佬，想借这个issue问一下。我正在学习和使用VirtualApp，但没法对 VAppClient 设置断点。即使是自己写的带调试符号的，也不行(Attach 也会失败)。想请问一下应该怎么调试 VAppClient.
非常感谢
