### ISSUE TITLE
百度地图SDK引发崩溃

### ISSUE THREAD

**Issue by codehz** [asLody/VirtualApp#215]
```
E/uncaught: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.netease.onmyoji/com.netease.onmyoji.Client}: java.lang.NullPointerException: Attempt to read from null array
                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2680)
                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2741)
                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                 at android.os.Looper.loop(Looper.java:154)
                                                 at android.app.ActivityThread.main(ActivityThread.java:6176)
                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
                                              Caused by: java.lang.NullPointerException: Attempt to read from null array
                                                 at com.baidu.platform.comapi.util.a.a(Unknown Source)
                                                 at com.baidu.platform.comapi.util.a.a(Unknown Source)
                                                 at com.baidu.platform.comapi.util.PermissionCheck.init(Unknown Source)
                                                 at com.baidu.platform.comapi.a.c(Unknown Source)
                                                 at com.baidu.platform.comapi.c.a(Unknown Source)
                                                 at com.baidu.mapapi.SDKInitializer.initialize(Unknown Source)
                                                 at com.baidu.mapapi.SDKInitializer.initialize(Unknown Source)
                                                 at com.netease.onmyoji.Client.onCreate(Client.java:441)
                                                 at android.app.Activity.performCreate(Activity.java:6679)
                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                 at com.lody.virtual.client.hook.delegate.InstrumentationDelegate.callActivityOnCreate(InstrumentationDelegate.java:244)
                                                 at com.lody.virtual.client.hook.delegate.AppInstrumentation.callActivityOnCreate(AppInstrumentation.java:88)
                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2633)
                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2741) 
                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488) 
                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                 at android.os.Looper.loop(Looper.java:154) 
                                                 at android.app.ActivityThread.main(ActivityThread.java:6176) 
                                                 at java.lang.reflect.Method.invoke(Native Method
```
不确定是否是普遍现象，但是我正在尝试手动使用百度地图的SDK

**Comment by asLody** [comment]
请测试一下今天的code.

**Comment by codehz** [comment]
大概这个百度SDK的问题是解决了，然而测试阴阳师还是跑不了——无法联网。。。。要不开个新的issue? @asLody
