### ISSUE TITLE
一个致命的问题

### ISSUE THREAD

**Issue by jksjdkfjkdsjkkk** [asLody/VirtualApp#228]
如果主程序(例如微信)被系统回收或者被强制杀死，这个虚拟引擎的那个应用就无法打开

例如我用VirtualApp双开了一个微信，打开这个双开微信，然后去设置里面强行停止微信官方程序，这个时候这个双开的微信就无法使用。 

机型:华为Mate9 安卓7.0

E/uncaught: java.lang.IllegalStateException: Token is exist!
                                                                            at android.os.Parcel.readException(Parcel.java:1694)
                                                                            at android.os.Parcel.readException(Parcel.java:1639)
                                                                            at com.lody.virtual.server.IActivityManager$Stub$Proxy.startService(IActivityManager.java:1360)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.lody.virtual.client.ipc.LocalProxyUtils$1.invoke(LocalProxyUtils.java:28)
                                                                            at java.lang.reflect.Proxy.invoke(Proxy.java:813)
                                                                            at $Proxy4.startService(Unknown Source)
                                                                            at com.lody.virtual.client.ipc.VActivityManager.startService(VActivityManager.java:170)
                                                                            at com.lody.virtual.client.hook.patchs.am.StartService.call(StartService.java:47)
                                                                            at com.lody.virtual.client.hook.base.HookDelegate$HookHandler.invoke(HookDelegate.java:150)
                                                                            at java.lang.reflect.Proxy.invoke(Proxy.java:813)
                                                                            at $Proxy7.startService(Unknown Source)
                                                                            at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1546)
                                                                            at android.app.ContextImpl.startService(ContextImpl.java:1528)
                                                                            at android.content.ContextWrapper.startService(ContextWrapper.java:613)
                                                                            at com.tencent.mm.booter.b.s(SourceFile:43)
                                                                            at com.tencent.mm.app.c.ad(SourceFile:112)
                                                                            at com.tencent.mm.plugin.zero.b$2.a(SourceFile:225)
                                                                            at com.tencent.mm.kernel.g$b$2.an(SourceFile:153)
                                                                            at com.tencent.mm.av.a.a(SourceFile:48)
                                                                            at com.tencent.mm.kernel.g$b.a(SourceFile:153)
                                                                            at com.tencent.mm.u.n.b(SourceFile:449)
                                                                            at com.tencent.mm.u.n.a(SourceFile:376)
                                                                            at com.tencent.mm.plugin.freewifi.d.c.b(SourceFile:76)
                                                                            at com.tencent.mm.plugin.freewifi.model.j$9.a(SourceFile:301)
                                                                            at com.tencent.mm.plugin.freewifi.model.j$9.a(SourceFile:298)
                                                                            at com.tencent.mm.sdk.c.a.a(SourceFile:230)
                                                                            at com.tencent.mm.sdk.c.a.z(SourceFile:163)
                                                                            at com.tencent.mm.ui.conversation.d$48.run(SourceFile:2591)
                                                                            at com.tencent.mm.sdk.platformtools.aj.run(SourceFile:127)
                                                                            at android.os.Handler.handleCallback(Handler.java:761)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                            at com.tencent.mm.sdk.platformtools.af.dispatchMessage(SourceFile:117)
                                                                            at android.os.Looper.loop(Looper.java:156)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by jksjdkfjkdsjkkk** [comment]
这回更惨，应用都没看到了，IOUniformer.cpp改的那些代码也要加吗？好像mate9用IOUniformer会报错，我都屏蔽了

**Comment by jksjdkfjkdsjkkk** [comment]
这个问题是启动的程序没有被杀死，例如p0,p1....。用了个坑爹的方法，就是VAPP启动的时候把那些乱七八糟的进程全杀了
