### ISSUE TITLE
本地应用卸载或升级后 会有运行时错误报出

### ISSUE THREAD

**Issue by youtouAshu** [asLody/VirtualApp#260]
如果添加的是手机上已经安装的应用，当该应用卸载或者进行更新就无法正常打开分身的app
会有运行时错误报出  按照爆出的错误应该是没有获取到这个包名的信息， 卸载的暂且不论 更新后的应该也是同一个包名 为什么信息没有办法获取到
java.lang.RuntimeException: android.content.pm.PackageManager$NameNotFoundException: Application package test.testupdate not found
                                                                 at com.lody.virtual.client.VClientImpl.createPackageContext(VClientImpl.java:358)
                                                                 at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:241)
                                                                 at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:178)
                                                                 at com.lody.virtual.client.hook.patchs.am.HCallbackHook.handleLaunchActivity(HCallbackHook.java:114)
                                                                 at com.lody.virtual.client.hook.patchs.am.HCallbackHook.handleMessage(HCallbackHook.java:71)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                 at android.os.Looper.loop(Looper.java:224)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5929)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
                                                              Caused by: android.content.pm.PackageManager$NameNotFoundException: Application package test.testupdate not found
                                                                 at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2421)
                                                                 at android.app.ContextImpl.createPackageContext(ContextImpl.java:2387)
                                                                 at com.lody.virtual.client.VClientImpl.createPackageContext(VClientImpl.java:356)
                                                                 at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:241)?
                                                                 at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:178)?
                                                                 at com.lody.virtual.client.hook.patchs.am.HCallbackHook.handleLaunchActivity(HCallbackHook.java:114)?
                                                                 at com.lody.virtual.client.hook.patchs.am.HCallbackHook.handleMessage(HCallbackHook.java:71)?
                                                                 at android.os.Handler.dispatchMessage(Handler.java:107)?
                                                                 at android.os.Looper.loop(Looper.java:224)?
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5929)?
                                                                 at java.lang.reflect.Method.invoke(Native Method)?
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)?
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)?
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)?

**Comment by cddjr** [comment]
因为更新后，apk路径会改变。 我去年的做法是接收系统的APP增、删广播，根据广播做处理。 
比如系统更新apk时，会首先广播删除，然后再广播新增。VA在收到删除广播时，临时杀掉VA中对应的app，并置其状态无效，如果随后收到了该app的新增广播，则重置状态，并重新安装一次该虚拟的APP(因为更新apk可能会产生新的so或者改变了文件名)。   具体细节就不表了，因为可能实现得不够好，我就不打算PR了

**Comment by perfactwork** [comment]
我也是监听的广播来做的，更新或者卸载后路径变了
