### ISSUE TITLE
Clone和从sdcard上安装???

### ISSUE THREAD

**Issue by qipeng090** [asLody/VirtualApp#263]
测试了一下百度地图最新版，clone的能打开并正常运行，把手机上的删掉，从sdcard上安装的却一直停在打开界面无法正常运行。
另外，发现在从手机clone后，每次第一次打开都闪退，再次打开就ok。

手机机型为Android4.4  Nexus5，官方ROM

补充：
或许真是机型问题，小米5的6.0系统就没有问题

**Comment by qipeng090** [comment]
03-31 14:56:30.841 22979-22979/io.virtualapp:p0 D/NativeEngine: DexOrJarPath = /data/app/com.auto.locationtest-2.apk, OutputPath = null.
03-31 14:56:30.861 22979-22979/io.virtualapp:p0 W/PackageManager: Failure retrieving text 0x7f060021 in package com.auto.locationtest
                                                                  java.lang.NullPointerException
                                                                      at android.content.res.AssetManager.addAssetPathNative(Native Method)
                                                                      at android.content.res.AssetManager.addAssetPath(AssetManager.java:607)
                                                                      at android.app.ResourcesManager.getTopLevelResources(ResourcesManager.java:179)
                                                                      at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1735)
                                                                      at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:775)
                                                                      at android.app.ApplicationPackageManager.getText(ApplicationPackageManager.java:993)
                                                                      at android.content.pm.ComponentInfo.loadLabel(ComponentInfo.java:94)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2121)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2226)
                                                                      at android.app.ActivityThread.access$700(ActivityThread.java:135)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1397)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:137)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:4998)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:777)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:593)
                                                                      at dalvik.system.NativeStart.main(Native Method)

**Comment by qipeng090** [comment]
5-03 20:58:10.827 32660-330/io.virtualapp:p0 E/SQLiteLog: (14) cannot open file at line 30191 of [00bb9c9ce4]
05-03 20:58:10.827 32660-330/io.virtualapp:p0 E/SQLiteLog: (14) os_unix.c:30191: (2) open(/data/data/com.baidu.BaiduMap/databases/datacenter.db) - 
05-03 20:58:10.827 32660-330/io.virtualapp:p0 E/SQLiteDatabase: Failed to open database '/data/data/com.baidu.BaiduMap/databases/datacenter.db'.
                                                                android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
                                                                    at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
                                                                    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
                                                                    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
                                                                    at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                                    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                                    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                    at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
                                                                    at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
                                                                    at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                                                                    at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:669)
                                                                    at com.baidu.mapframework.e.a.c.d(SourceFile:69)
                                                                    at com.baidu.mapframework.e.c.a.b(SourceFile:295)
                                                                    at com.baidu.mapframework.e.c.a.a(SourceFile:49)
                                                                    at com.baidu.mapframework.e.c.a.<init>(SourceFile:45)
                                                                    at com.baidu.mapframework.e.a.b(SourceFile:30)
                                                                    at com.baidu.baidumaps.BaiduMapApplication$1.run(SourceFile:298)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                    at java.lang.Thread.run(Thread.java:841)
                                                                    at com.baidu.platform.basic.b.run(SourceFile:61)
                                                                    at com.baidu.platform.comapi.util.f$1.run(SourceFile:35)

**Comment by kundandas** [comment]
Were you able to fix this issue? If yes, how?
