### ISSUE TITLE
夜神模拟器安装插件闪退

### ISSUE THREAD

**Issue by dovewi** [asLody/VirtualApp#315]
```
05-21 11:32:05.935 4053-4053/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.dobe.sandbox, PID: 4053
                                                 java.lang.RuntimeException: Failure delivering result ResultInfo{who=android:fragment:0, request=5, result=-1, data=Intent { (has extras) }} to activity {com.dobe.sandbox/io.virtualapp.home.MainActivity}: com.lody.virtual.client.env.DeadServerException: android.os.DeadObjectException
                                                     at android.app.ActivityThread.deliverResults(ActivityThread.java:3363)
                                                     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3406)
                                                     at android.app.ActivityThread.access$1300(ActivityThread.java:135)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1244)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5019)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: com.lody.virtual.client.env.DeadServerException: android.os.DeadObjectException
                                                     at com.lody.virtual.client.env.VirtualRuntime.crash(VirtualRuntime.java:61)
                                                     at com.lody.virtual.client.core.VirtualCore.getInstalledAppInfo(VirtualCore.java:501)
                                                     at io.virtualapp.home.DesktopFragment.onActivityResult(DesktopFragment.java:94)
                                                     at android.app.Activity.dispatchActivityResult(Activity.java:5427)
                                                     at android.app.ActivityThread.deliverResults(ActivityThread.java:3359)
                                                     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3406) 
                                                     at android.app.ActivityThread.access$1300(ActivityThread.java:135) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1244) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5019) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: android.os.DeadObjectException
                                                     at android.os.BinderProxy.transact(Native Method)
                                                     at com.lody.virtual.server.IAppManager$Stub$Proxy.getInstalledAppInfo(IAppManager.java:386)
                                                     at com.lody.virtual.client.core.VirtualCore.getInstalledAppInfo(VirtualCore.java:499)
                                                     at io.virtualapp.home.DesktopFragment.onActivityResult(DesktopFragment.java:94) 
                                                     at android.app.Activity.dispatchActivityResult(Activity.java:5427) 
                                                     at android.app.ActivityThread.deliverResults(ActivityThread.java:3359) 
                                                     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3406) 
                                                     at android.app.ActivityThread.access$1300(ActivityThread.java:135) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1244) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5019) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by perfactwork** [comment]
x进程的远端Ibinder对象挂掉了，添加linktodeath即可

**Comment by dovewi** [comment]
@perfactwork 具体怎么搞啊，没仔细研究源码，不知道在哪儿改。

**Comment by perfactwork** [comment]
@dovewi 在ServiceManagerNative这个类，模仿linkBinderDied这个方法就行，fetcher.getService(name)这个获取的也是Ibinder对象，有时候会意外挂掉，所以也需要进行挂掉的时候重新获取
