### ISSUE TITLE
VA跨进程通信的地方太不稳定了,好多机型闪退

### ISSUE THREAD

**Issue by dovewi** [asLody/VirtualApp#344]
问题就是server和client通信时候产生的DeadObjectException.

有没有考虑过换别的更稳定点的方式实现

很多机型,还有模拟器,动不动就闪退死了

**Comment by dovewi** [comment]
```
08-08 07:11:55.663 7954-8173/? E/VirtualRuntime: crash: 
                                                 android.os.DeadObjectException
                                                     at android.os.BinderProxy.transact(Native Method)
                                                     at com.lody.virtual.server.IPackageManager$Stub$Proxy.getInstalledPackages(IPackageManager.java:1010)
                                                     at com.lody.virtual.client.ipc.VPackageManager.getInstalledPackages(VPackageManager.java:124)
                                                     at com.lody.virtual.client.hook.proxies.pm.MethodProxies$GetInstalledPackages.call(MethodProxies.java:1079)
                                                     at com.lody.virtual.client.hook.base.MethodInvocationStub$HookInvocationHandler.invoke(MethodInvocationStub.java:186)
                                                     at $Proxy5.getInstalledPackages(Native Method)
                                                     at android.app.ApplicationPackageManager.getInstalledPackages(ApplicationPackageManager.java:445)
                                                     at android.app.ApplicationPackageManager.getInstalledPackages(ApplicationPackageManager.java:438)
                                                     at com.meituan.android.common.unionid.oneid.OneIdHelper.getPackageNameList(OneIdHelper.java:320)
                                                     at com.meituan.android.common.unionid.oneid.OneIdHelper.updateOneIdToAll(OneIdHelper.java:270)
                                                     at com.meituan.android.common.unionid.oneid.OneIdHelper.getOneIdByLocal(OneIdHelper.java:103)
                                                     at com.meituan.android.common.unionid.oneid.OneIdHelper.registerOrUpdate(OneIdHelper.java:378)
                                                     at com.meituan.android.common.unionid.oneid.OneIdHandler$3.run(OneIdHandler.java:133)
                                                     at java.lang.Thread.run(Thread.java:841)
08-08 07:11:55.673 7903-8125/io.virtualapp:p0 W/System.err: android.os.DeadObjectException
08-08 07:11:55.733 7903-8125/? E/VirtualRuntime: crash: 
                                                 android.os.DeadObjectException
                                                     at android.os.BinderProxy.transact(Native Method)
                                                     at com.lody.virtual.server.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:658)
                                                     at com.lody.virtual.client.ipc.VPackageManager.getPackageInfo(VPackageManager.java:92)
                                                     at com.lody.virtual.client.hook.proxies.pm.MethodProxies$GetPackageInfo.call(MethodProxies.java:636)
                                                     at com.lody.virtual.client.hook.base.MethodInvocationStub$HookInvocationHandler.invoke(MethodInvocationStub.java:186)
                                                     at $Proxy5.getPackageInfo(Native Method)
                                                     at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:74)
                                                     at com.meituan.android.common.fingerprint.FingerprintManager.lambda$setFingerprintInfo$51(ProGuard:290)
                                                     at com.meituan.android.common.fingerprint.FingerprintManager.access$lambda$53(ProGuard)
                                                     at com.meituan.android.common.fingerprint.FingerprintManager$$Lambda$58.get(Unknown Source)
                                                     at com.meituan.android.common.fingerprint.info.FingerprintInfo.getFingerItem(ProGuard:453)
                                                     at com.meituan.android.common.fingerprint.info.FingerprintInfo.setAppVersion(ProGuard:432)
                                                     at com.meituan.android.common.fingerprint.FingerprintManager.setFingerprintInfo(ProGuard:288)
                                                     at com.meituan.android.common.fingerprint.FingerprintManager.fingerprint(ProGuard:88)
                                                     at dbq.a(ProGuard:291)
                                                     at com.sankuai.meituan.takeoutnew.ui.page.boot.WelcomeActivity.g(ProGuard:483)
                                                     at com.sankuai.meituan.takeoutnew.ui.page.boot.WelcomeActivity.g(ProGuard:87)
                                                     at com.sankuai.meituan.takeoutnew.ui.page.boot.WelcomeActivity$9.a(ProGuard:454)
                                                     at dvd$c.a(ProGuard:92)
                                                     at dvd$c.doInBackground(ProGuard:61)
                                                     at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                     at java.lang.Thread.run(Thread.java:841)
```

**Comment by liupeng110** [comment]
饿了么封装那个eventbus跨app通信  试试怎么样

**Comment by dovewi** [comment]
支持楼上,希望考虑考虑换个实现方式,不然总不停闪退很恼火啊

**Comment by asLody** [comment]
与实现方式无关
