### ISSUE TITLE
Nexus 6p升级到Android O 后，VirtualApp安装应用崩溃

### ISSUE THREAD

**Issue by c1024** [asLody/VirtualApp#363]
之前Nexus 6p是Android N系统，用VirtualApp安装应用可以正常使用。升级到Android O后，安装应用直接崩溃。
崩溃信息如下：
 java.lang.NullPointerException: Attempt to invoke virtual method 'void mirror.RefObject.set(java.lang.Object, java.lang.Object)' on a null object reference
                                                                   at android.os.Parcel.readException(Parcel.java:1948)
                                                                   at android.os.Parcel.readException(Parcel.java:1888)
                                                                   at com.lody.virtual.server.IPackageManager$Stub$Proxy.getApplicationInfo(IPackageManager.java:1170)
                                                                   at com.lody.virtual.client.ipc.VPackageManager.getApplicationInfo(VPackageManager.java:182)
                                                                   at com.lody.virtual.remote.InstalledAppInfo.getApplicationInfo(InstalledAppInfo.java:39)
                                                                   at io.virtualapp.home.models.PackageAppData.<init>(PackageAppData.java:25)
                                                                   at io.virtualapp.home.repo.PackageAppDataStorage.loadAppData(PackageAppDataStorage.java:48)
                                                                   at io.virtualapp.home.repo.PackageAppDataStorage.acquire(PackageAppDataStorage.java:33)
                                                                   at io.virtualapp.home.HomePresenterImpl.lambda$addApp$1(HomePresenterImpl.java:149)
                                                                   at io.virtualapp.home.HomePresenterImpl$$Lambda$6.onDone(Unknown Source:6)
                                                                   at org.jdeferred.android.AndroidDeferredObject$InternalHandler.handleMessage(AndroidDeferredObject.java:82)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                   at android.os.Looper.loop(Looper.java:164)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by asLody** [comment]
Fixed.
