### ISSUE TITLE
whatsapp 设置头像调用相机崩溃

### ISSUE THREAD

**Issue by qianyukun** [asLody/VirtualApp#368]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.whatsapp/com.whatsapp.CapturePhoto}: java.lang.SecurityException: Uid 11040 does not have permission to uri 0 @ content://com.whatsapp.fileprovider/external/WhatsApp/.Shared/tmpi
                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                            at android.os.Handler.dispatchMessage(Handler.java:105)
                                                            at android.os.Looper.loop(Looper.java:156)
                                                            at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                         Caused by: java.lang.SecurityException: Uid 11040 does not have permission to uri 0 @ content://com.whatsapp.fileprovider/external/WhatsApp/.Shared/tmpi
                                                            at android.os.Parcel.readException(Parcel.java:1665)
                                                            at android.os.Parcel.readException(Parcel.java:1618)
                                                            at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3097)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at com.lody.virtual.client.hook.proxies.am.MethodProxies$StartActivity.call(MethodProxies.java:441)
                                                            at com.lody.virtual.client.hook.base.MethodInvocationStub$HookInvocationHandler.invoke(MethodInvocationStub.java:186)
                                                            at java.lang.reflect.Proxy.invoke(Proxy.java:813)
                                                            at $Proxy6.startActivity(Unknown Source)
                                                            at android.app.Instrumentation.execStartActivity(Instrumentation.java:1539)
                                                            at android.app.Activity.startActivityForResult(Activity.java:4391)
                                                            at android.support.v4.app.e.startActivityForResult(BaseFragmentActivityApi16.java:54)
                                                            at android.support.v4.app.g.startActivityForResult(FragmentActivity.java:65)
                                                            at android.app.Activity.startActivityForResult(Activity.java:4335)
                                                            at android.support.v4.app.g.startActivityForResult(FragmentActivity.java:711)
                                                            at com.whatsapp.CapturePhoto.h(CapturePhoto.java:39)
                                                            at com.whatsapp.CapturePhoto.onCreate(CapturePhoto.java:28)
                                                            at android.app.Activity.performCreate(Activity.java:6910)
                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                            at com.lody.virtual.client.hook.delegate.InstrumentationDelegate.callActivityOnCreate(InstrumentationDelegate.java:244)
                                                            at com.lody.virtual.client.hook.delegate.AppInstrumentation.callActivityOnCreate(AppInstrumentation.java:92)
                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864) 
                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567) 
                                                            at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                            at android.os.Looper.loop(Looper.java:156) 
                                                            at android.app.ActivityThread.main(ActivityThread.java:6523) 
                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by jeepc** [comment]
只要是用这个https://developer.android.com/about/versions/nougat/android-7.0-changes.html#sharing-files方式共享文件都会报这个错误
