### ISSUE TITLE
kindle for android 使用网络下载时crash

### ISSUE THREAD

**Issue by nkwsqyyzx** [asLody/VirtualApp#369]
20:58:25.286 20987                  uncaught E java.lang.SecurityException: NetworkStats: Neither user 10106 nor current process has android.permission.MODIFY_NETWORK_ACCOUNTING.
20:58:25.286 20987                  uncaught E 	at android.os.Parcel.readException(Parcel.java:1665)
20:58:25.286 20987                  uncaught E 	at android.os.Parcel.readException(Parcel.java:1618)
20:58:25.286 20987                  uncaught E 	at android.net.INetworkStatsService$Stub$Proxy.incrementOperationCount(INetworkStatsService.java:340)
20:58:25.286 20987                  uncaught E 	at android.net.TrafficStats.incrementOperationCount(TrafficStats.java:324)
20:58:25.286 20987                  uncaught E 	at android.net.TrafficStats.incrementOperationCount(TrafficStats.java:311)
20:58:25.286 20987                  uncaught E 	at com.amazon.android.providers.downloads.DownloadThread.runDownload(DownloadThread.java:602)
20:58:25.286 20987                  uncaught E 	at com.amazon.android.providers.downloads.DownloadThread.run(DownloadThread.java:410)
20:58:25.293 20987                       art I System.exit called, status: 0
20:58:25.293 20987            AndroidRuntime I VM exiting with result code 0, cleanup skipped.

**Comment by nkwsqyyzx** [comment]
api level: 24
