### ISSUE TITLE
微信的密码输入框无法弹出输入法

### ISSUE THREAD

**Issue by huwentao** [asLody/VirtualApp#371]
在VirtualApp中安装微信后登录的密码输入框点击不能弹出密码输入键盘，使用的手机是华为V8 系统是EMUI5.0.1  安卓版本是7.0 ，代码版本是最新拉取的

**Comment by mingio** [comment]
腾讯视频的搜索框也不能弹出输入键盘，现象是点击输入框就完全黑屏。
android 7.1.1
moto z play2
腾讯视频5.1.0.11150

**Comment by asLody** [comment]
any crash log?

**Comment by huwentao** [comment]
微信的密码输入框只是弹不出密码键盘没有错误log也没有出现黑屏，试过QQ的密码输入键盘没有问题，

**Comment by siweg** [comment]
微信6.5.16版，在多个安卓7上出现能弹出密码键盘但无法输入, 这个log可能有用:
10-11 16:41:29.255 880-4188/? W/AppOps: Bad call: specified package com.tencent.mm under uid 10164 but it is really 10186
                                        java.lang.RuntimeException: here
                                            at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1257)
                                            at com.android.server.AppOpsService.checkPackage(AppOpsService.java:976)
                                            at android.app.AppOpsManager.checkPackage(AppOpsManager.java:1656)
                                            at com.android.internal.inputmethod.InputMethodUtils.checkIfPackageBelongsToUid(InputMethodUtils.java:814)
                                            at com.android.server.InputMethodManagerService.startInputUncheckedLocked(InputMethodManagerService.java:1383)
                                            at com.android.server.InputMethodManagerService.windowGainedFocus(InputMethodManagerService.java:2397)
                                            at com.android.server.InputMethodManagerService.startInputOrWindowGainedFocus(InputMethodManagerService.java:2240)
                                            at com.android.internal.view.IInputMethodManager$Stub.onTransact(IInputMethodManager.java:198)
                                            at com.android.server.InputMethodManagerService.onTransact(InputMethodManagerService.java:1065)
                                            at android.os.Binder.execTransact(Binder.java:565)
10-11 16:41:29.255 880-4188/? E/InputMethodManagerService: Rejecting this client as it reported an invalid package name. uid=10164 package=com.tencent.mm

**Comment by siweg** [comment]
微信6.5.6, 在多个安卓7手机上能弹出密码键盘但无法输入, 这个log可能有关:
![wechat](https://user-images.githubusercontent.com/25816210/31430934-ead70d2a-ae37-11e7-803f-ddecbde7e3ed.png)

**Comment by huwentao** [comment]
拿vivo的机器微信的密码键盘又能弹出，就是华为的不行，日志没看到什么错误，已经把所有日志传上来了
[日志.txt](https://github.com/asLody/VirtualApp/files/1377912/default.txt)
