### ISSUE TITLE
Amap will crash when starting up while running on samsung devices

### ISSUE THREAD

**Issue by lolicon** [asLody/VirtualApp#386]
while startup, amap performing `setServiceForeground` twice for service `com.taobao.accs.ChannelService` and `com.taobao.accs.ChannelService$KernelService` and then stopSelf for the later to enhance the oomadj and remove foreground service notification

in Samsung SystemUI.apk 
the 2nd call to `setServiceForeground` will call `BaseStatusBar#updateNotification` and evetuanlly
invoke chunk of code below
```
 statusbarIcon = new StatusBarIcon(...,newNotification.icon, ...);
```

comparing to AOSP http://androidxref.com/6.0.1_r10/xref/frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/BaseStatusBar.java#1929

notice the `newNotification.icon` was not what we set in our code, but from notification.getSmallIcon().getResId() 

so in line 1790, SystemUI propagation crashes to the :x process

**Comment by lolicon** [comment]
```
ResourceType: No package identifier when getting value for resource number 0x00000000
Icon    : Unable to load resource 0x00000000 from pkg=io.virtualapp
Icon    : android.content.res.Resources$NotFoundException: Resource ID #0x0
Icon    :      at android.content.res.Resources.getValue(Resources.java:2558)
Icon    :      at android.content.res.Resources.getDrawable(Resources.java:2001)
Icon    :      at android.content.res.Resources.getDrawable(Resources.java:1987)
Icon    :      at android.graphics.drawable.Icon.loadDrawableInner(Icon.java:313)
Icon    :      at android.graphics.drawable.Icon.loadDrawable(Icon.java:269)
Icon    :      at android.graphics.drawable.Icon.loadDrawableAsUser(Icon.java:377)
Icon    :      at com.android.systemui.statusbar.StatusBarIconView.getIcon(StatusBarIconView.java:197)
Icon    :      at com.android.systemui.statusbar.StatusBarIconView.getIcon(StatusBarIconView.java:182)
Icon    :      at com.android.systemui.statusbar.StatusBarIconView.updateDrawable(StatusBarIconView.java:169)
Icon    :      at com.android.systemui.statusbar.StatusBarIconView.set(StatusBarIconView.java:138)
Icon    :      at com.android.systemui.statusbar.BaseStatusBar.updateNotification(BaseStatusBar.java:3969)
Icon    :      at com.android.systemui.statusbar.BaseStatusBar$7$2.run(BaseStatusBar.java:1263)
Icon    :      at android.os.Handler.handleCallback(Handler.java:739)
Icon    :      at android.os.Handler.dispatchMessage(Handler.java:95)
Icon    :      at android.os.Looper.loop(Looper.java:158)
Icon    :      at android.app.ActivityThread.main(ActivityThread.java:7225)
Icon    :      at java.lang.reflect.Method.invoke(Native Method)
Icon    :      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
Icon    :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
StatusBarIconView: No icon for slot io.virtualapp/0x249b
```

above lists the stacktrace in SystemUI , so in samsung devices, when you update notification via setForeground
the system *only* accept smallIcon with RESOURCE type, no BITMAP type was allowed 
since NotificationFixer fix resource type to BITMAP, it increase this risk

**Comment by lolicon** [comment]
all applications using umeng push service on samsung device will be affected by this issue, not just amap

**Comment by asLody** [comment]
Good job!
