### ISSUE TITLE
360手机助手双开失败  

### ISSUE THREAD

**Issue by liupeng110** [asLody/VirtualApp#407]
.qihoo.appstore I/System.out: Close in OkHttp
11-06 11:20:01.523 27796-27902/com.qihoo.appstore I/System.out: http://sdk.s.360.cn/ak/3416a75f4cea9109507cacd8e2f2aefc.html?m2=8e5bf9392b2055d28ca6eb169a3237b2
11-06 11:20:01.641 27796-27796/com.qihoo.appstore W/ws001: NRH lcl.fc: c=com.ak.e.b.d
11-06 11:20:01.644 27796-27928/com.qihoo.appstore W/ws001: NRH lcl.fc: c=com.ak.e.a.e
11-06 11:20:01.645 27796-27929/com.qihoo.appstore W/ws001: NRH lcl.fc: c=com.ak.e.a.e
11-06 11:20:01.796 27796-27923/com.qihoo.appstore I/OpenGLRenderer: Initialized EGL, version 1.4
11-06 11:20:01.807 27796-27923/com.qihoo.appstore E/OpenGLRenderer: PerfServiceNative_notifyRenderTime init fail!
11-06 11:20:01.808 27796-27923/com.qihoo.appstore I/OpenGLRenderer: Get enable program binary service property (1)
11-06 11:20:01.809 27796-27923/com.qihoo.appstore I/OpenGLRenderer: Program binary detail: Binary length is 173456, program map length is 152.
11-06 11:20:01.810 27796-27923/com.qihoo.appstore I/OpenGLRenderer: Succeeded to mmap program binaries. File descriptor is 63, and path is /dev/ashmem.
11-06 11:20:01.810 27796-27923/com.qihoo.appstore I/OpenGLRenderer: No need to use file discriptor anymore, close fd(63).
11-06 11:20:01.811 27796-27923/com.qihoo.appstore W/libEGL: [ANDROID_RECORDABLE] format: 1
11-06 11:20:01.922 27796-27900/com.qihoo.appstore I/System.out: http://s.360.cn/zhushou/service.htm?service=features&v=7.1.9&m2=4027445fca12ae25987ceafe9756896e&md=M5&campaign=2&src=1&page=no_show_ad&f=no_hava_ad
11-06 11:20:01.960 27796-27900/com.qihoo.appstore I/System.out: Close in OkHttp
11-06 11:20:02.078 27796-27953/com.qihoo.appstore I/System.out: http://openbox.mobilem.360.cn/Inew/newBanner/?ad=3&tm=-1&from=0&os=23&vc=300070109&v=7.1.9&os_version=6.0&md=M5&sn=4.589389937671455&cpu=mt6750&ca1=armeabi-v7a&ca2=armeabi&m=ae848b1b630e2225abee8b893db4d000&m2=4027445fca12ae25987ceafe9756896e&ch=8967319&ppi=720_1280&startCount=1&re=1&tid=0&cpc=1&snt=-1&nt=1&gender=-1&age=-1&theme=2&br=Meizu&s_3pk=1&webp=1
11-06 11:20:02.137 27796-27973/com.qihoo.appstore I/System.out: http://p7.qhimg.com/t01f3bd1e304a95b9c2.jpg
11-06 11:20:02.169 27796-27923/com.qihoo.appstore W/libEGL: [ANDROID_RECORDABLE] format: 1
11-06 11:20:02.181 27796-27808/com.qihoo.appstore I/ws001: p.p d, p.h s n
11-06 11:20:02.185 27796-27950/com.qihoo.appstore E/ws001: mp.pded: null
                                                           android.os.DeadObjectException
                                                               at android.os.BinderProxy.transactNative(Native Method)
                                                               at android.os.BinderProxy.transact(Binder.java:514)
                                                               at com.qihoo360.loader2.f$a$a.b(AppStore)
                                                               at com.qihoo360.loader2.i.a(AppStore)
                                                               at com.qihoo360.replugin.RePlugin.install(AppStore)
                                                               at com.qihoo.k.b.a(AppStore)
                                                               at com.qihoo.k.i$b.a(AppStore)
                                                               at com.qihoo.k.i$b.doInBackground(AppStore)
                                                               at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                               at java.lang.Thread.run(Thread.java:818)
11-06 11:20:02.287 27796-27923/com.qihoo.appstore E/Surface: getSlotFromBufferLocked: unknown buffer: 0xdc5066a0
11-06 11:20:02.312 27796-27923/com.qihoo.appstore W/libEGL: [ANDROID_RECORDABLE] format: 1
11-06 11:20:02.535 27796-27892/com.qihoo.appstore E/ActivityThread: Failed to find provider info for 360secstoreignoreappinfo
11-06 11:20:02.536 27796-27892/com.qihoo.appstore E/ActivityThread: Failed to find provider info for 360outersecstoresingleignoreappinfo
11-06 11:20:02.557 27796-27892/com.qihoo.appstore E/SQLiteLog: (1) no such table: appinfo
11-06 11:20:02.596 27796-27892/com.qihoo.appstore E/ActivityThread: Failed to find provider info for 360outersecstoresingleignoreappinfo
11-06 11:20:02.597 27796-27892/com.qihoo.appstore E/ActivityThread: Failed to find provider info for 360secstoreignoreappinfo
11-06 11:20:02.864 27796-27902/com.qihoo.appstore W/System.err: java.lang.InstantiationException: java.lang.Class<com.qihoo.m.a> has no zero argument constructor
11-06 11:20:02.864 27796-27902/com.qihoo.appstore W/System.err:     at java.lang.Class.newInstance(Native Method)
11-06 11:20:02.864 27796-27902/com.qihoo.appstore W/System.err:     at com.qihoo.sdk.report.common.d.a(AppStore)
11-06 11:20:02.864 27796-27902/com.qihoo.appstore W/System.err:     at com.qihoo.sdk.report.b.a$1.run(AppStore)
11-06 11:20:02.864 27796-27902/com.qihoo.appstore W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-06 11:20:02.864 27796-27902/com.qihoo.appstore W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-06 11:20:02.864 27796-27902/com.qihoo.appstore W/System.err:     at java.lang.Thread.run(Thread.java:818)
11-06 11:20:02.896 27796-27902/com.qihoo.appstore W/System.err: java.lang.InstantiationException: java.lang.Class<com.qihoo.m.a> has no zero argument constructor
11-06 11:20:02.896 27796-27902/com.qihoo.appstore W/System.err:     at java.lang.Class.newInstance(Native Method)
11-06 11:20:02.896 27796-27902/com.qihoo.appstore W/System.err:     at com.qihoo.sdk.report.common.d.a(AppStore)
11-06 11:20:02.896 27796-27902/com.qihoo.appstore W/System.err:     at com.qihoo.sdk.report.b.a$1.run(AppStore)
11-06 11:20:02.896 27796-27902/com.qihoo.appstore W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-06 11:20:02.896 27796-27902/com.qihoo.appstore W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-06 11:20:02.896 27796-27902/com.qihoo.appstore W/System.err:     at java.lang.Thread.run(Thread.java:818)
11-06 11:20:04.176 27796-27900/com.qihoo.appstore W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
11-06 11:20:04.176 27796-27900/com.qihoo.appstore W/System.err:     at android.text.TextUtils$SimpleStringSplitter.setString(TextUtils.java:425)
11-06 11:20:04.176 27796-27900/com.qihoo.appstore W/System.err:     at com.qihoo.appstore.accessibility.a.a(AppStore)
11-06 11:20:04.176 27796-27900/com.qihoo.appstore W/System.err:     at com.qihoo.appstore.base.AppStoreApplication$9.run(AppStore)
11-06 11:20:04.176 27796-27900/com.qihoo.appstore W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
11-06 11:20:04.176 27796-27900/com.qihoo.appstore W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-06 11:20:04.176 27796-27900/com.qihoo.appstore W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
11-06 11:20:04.176 27796-27900/com.qihoo.appstore W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
11-06 11:20:04.176 27796-27900/com.qihoo.appstore W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-06 11:20:04.176 27796-27900/com.qihoo.appstore W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-06 11:20:04.177 27796-27900/com.qihoo.appstore W/System.err:     at java.lang.Thread.run(Thread.java:818)
11-06 11:20:04.177 27796-27900/com.qihoo.appstore W/System.err:     at com.qihoo.utils.thread.b$1.run(AppStore)
11-06 11:20:04.264 27796-27923/com.qihoo.appstore E/Surface: getSlotFromBufferLocked: unknown buffer: 0xdc506e20
11-06 11:20:04.292 27796-27796/com.qihoo.appstore W/System.err: java.lang.NoSuchMethodException: registerScreenActionReceiver [class android.content.Context]
11-06 11:20:04.292 27796-27796/com.qihoo.appstore W/System.err:     at java.lang.Class.getMethod(Class.java:624)
11-06 11:20:04.292 27796-27796/com.qihoo.appstore W/System.err:     at java.lang.Class.getDeclaredMethod(Class.java:586)
11-06 11:20:04.292 27796-27796/com.qihoo.appstore W/System.err:     at com.stub.plugin.Stub02.onStartCommand(Native Method)
11-06 11:20:04.292 27796-27796/com.qihoo.appstore W/System.err:     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3334)
11-06 11:20:04.292 27796-27796/com.qihoo.appstore W/System.err:     at android.app.ActivityThread.access$2200(ActivityThread.java:189)
11-06 11:20:04.292 27796-27796/com.qihoo.appstore W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1686)
11-06 11:20:04.292 27796-27796/com.qihoo.appstore W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:111)
11-06 11:20:04.292 27796-27796/com.qihoo.appstore W/System.err:     at android.os.Looper.loop(Looper.java:207)
11-06 11:20:04.292 27796-27796/com.qihoo.appstore W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5896)
11-06 11:20:04.292 27796-27796/com.qihoo.appstore W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-06 11:20:04.292 27796-27796/com.qihoo.appstore W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:948)
11-06 11:20:04.292 27796-27796/com.qihoo.appstore W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)
11-06 11:20:04.350 27796-28016/com.qihoo.appstore I/System.out: isEmailSend:GET
11-06 11:20:04.358 27796-28016/com.qihoo.appstore I/System.out: openConnection:8
11-06 11:20:04.375 27796-28018/com.qihoo.appstore I/System.out: isEmailSend:POST
11-06 11:20:04.375 27796-28018/com.qihoo.appstore I/System.out: getAllHeaders:POST
11-06 11:20:04.375 27796-28018/com.qihoo.appstore I/System.out: httpHeader:Content-Type: application/x-www-form-urlencoded
11-06 11:20:04.381 27796-28018/com.qihoo.appstore I/System.out: openConnection:8
11-06 11:20:04.402 27796-28016/com.qihoo.appstore I/System.out: >doSendRequest
11-06 11:20:04.403 27796-28016/com.qihoo.appstore I/System.out: <doSendRequest
11-06 11:20:04.425 27796-28018/com.qihoo.appstore I/System.out: >doSendRequest
11-06 11:20:04.425 27796-28018/com.qihoo.appstore I/System.out: <doSendRequest
11-06 11:20:04.448 27796-28021/com.qihoo.appstore W/SettingsInterface: Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
11-06 11:20:04.490 27796-28018/com.qihoo.appstore I/System.out: <doReceiveResponse
11-06 11:20:04.490 27796-28016/com.qihoo.appstore I/System.out: <doReceiveResponse
11-06 11:20:04.796 27796-27900/com.qihoo.appstore E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 140)
11-06 11:20:04.796 27796-27900/com.qihoo.appstore W/System.err: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
11-06 11:20:04.797 27796-27900/com.qihoo.appstore W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
11-06 11:20:04.797 27796-27900/com.qihoo.appstore W/System.err:     at android.os.BinderProxy.transact(Binder.java:514)
11-06 11:20:04.797 27796-27900/com.qihoo.appstore W/System.err:     at com.lody.virtual.server.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:658)
11-06 11:20:04.797 27796-27900/com.qihoo.appstore W/System.err:     at com.lody.virtual.client.ipc.VPackageManager.getPackageInfo(VPackageManager.java:86)
11-06 11:20:04.797 27796-27900/com.qihoo.appstore W/System.err:     at com.lody.virtual.client.hook.proxies.pm.MethodProxies$GetPackageInfo.call(MethodProxies.java:636)
11-06 11:20:04.797 27796-27900/com.qihoo.appstore W/System.err:     at com.lody.virtual.client.hook.base.MethodInvocationStub$HookInvocationHandler.invoke(MethodInvocationStub.java:186)
11-06 11:20:04.797 27796-27900/com.qihoo.appstore W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:393)
11-06 11:20:04.797 27796-27900/com.qihoo.appstore W/System.err:     at $Proxy4.getPackageInfo(Unknown Source)
11-06 11:20:04.797 27796-27900/com.qihoo.appstore W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-06 11:20:04.797 27796-27900/com.qihoo.appstore W/System.err:     at com.morgoo.droidplugin.c.c.h.invoke(AppStore)
11-06 11:20:04.797 27796-27900/com.qihoo.appstore W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:393)
11-06 11:20:04.797 27796-27900/com.qihoo.appstore W/System.err:     at $Proxy44.getPackageInfo(Unknown Source)
11-06 11:20:04.798 27796-27900/com.qihoo.appstore W/System.err:     at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:140)
11-06 11:20:04.798 27796-27900/com.qihoo.appstore W/System.err:     at cn.com.iresearch.mapptracker.b.d.b(Unknown Source)
11-06 11:20:04.798 27796-27900/com.qihoo.appstore W/System.err:     at cn.com.iresearch.mapptracker.IRMonitor.a(Unknown Source)
11-06 11:20:04.798 27796-27900/com.qihoo.appstore W/System.err:     at cn.com.iresearch.mapptracker.IRMonitor.Init(Unknown Source)
11-06 11:20:04.798 27796-27900/com.qihoo.appstore W/System.err:     at com.qihoo.appstore.ae.a.a.a(AppStore)
11-06 11:20:04.798 27796-27900/com.qihoo.appstore W/System.err:     at com.qihoo.appstore.base.AppStoreApplication$9.run(AppStore)
11-06 11:20:04.798 27796-27900/com.qihoo.appstore W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
11-06 11:20:04.799 27796-27900/com.qihoo.appstore W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-06 11:20:04.799 27796-27900/com.qihoo.appstore W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
11-06 11:20:04.799 27796-27900/com.qihoo.appstore W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
11-06 11:20:04.799 27796-27900/com.qihoo.appstore W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-06 11:20:04.799 27796-27900/com.qihoo.appstore W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-06 11:20:04.799 27796-27900/com.qihoo.appstore W/System.err:     at java.lang.Thread.run(Thread.java:818)
11-06 11:20:04.799 27796-27900/com.qihoo.appstore W/System.err:     at com.qihoo.utils.thread.b$1.run(AppStore)
11-06 11:20:04.800 27796-27900/com.qihoo.appstore I/Process: Sending signal. PID: 27796 SIG: 9

**Comment by liupeng110** [comment]
![s71106-11210174](https://user-images.githubusercontent.com/9512550/32423994-b9a720ca-c2e4-11e7-9fb2-c3ee525ee24f.jpg)

**Comment by liupeng110** [comment]
android 6.0

**Comment by addhaloka** [comment]
YunOS?

**Comment by liupeng110** [comment]
@addhaloka  对,魅蓝5

**Comment by liupeng110** [comment]
360分身大师跟lbe平行空间 可以正常双开  好像是360手机助手针对va做了什么处理

**Comment by asLody** [comment]
我这边能正常运行。。。
