### ISSUE TITLE
克隆应用程序，然后从Playstore更新该应用程序会中断克隆

### ISSUE THREAD

**Issue by saharh** [asLody/VirtualApp#436]
1. Install Whatsapp (or any other app)
2. Clone it using VirtualApp
3. Once an update is available for Whatsapp, update it through play store
4. Try to run Clone

Result: Clone won't run, stuck in loop. Following error is shown:

12-20 18:49:13.200 1623-2862/? I/ActivityManager: Start proc 12288:com.example.app:p0/u0a93 for activity com.example.app/com.lody.virtual.client.stub.StubActivity$C0
12-20 18:49:13.210 12288-12293/? E/art: Failed sending reply to debugger: Broken pipe
12-20 18:49:13.210 12288-12293/? I/art: Debugger is no longer active
12-20 18:49:13.211 12288-12293/? I/art: Starting a blocking GC Instrumentation
12-20 18:49:13.306 12288-12288/? D/MethodInvocationStub: Unable to build HookDelegate: BinderInvocationStub.
12-20 18:49:13.310 12288-12288/? D/MethodInvocationStub: Unable to build HookDelegate: BinderInvocationStub.
12-20 18:49:13.320 12288-12288/? D/MethodInvocationStub: Unable to build HookDelegate: BinderInvocationStub.
12-20 18:49:13.340 12288-12288/? I/VClientImpl: Binding application com.whatsapp (com.whatsapp)
12-20 18:49:13.351 12288-12288/? D/VA++: do_dlopen : libart.so, return : 0x0.
12-20 18:49:13.332 12288-12288/? W/com.whatsapp: type=1400 audit(0.0:2216): avc: denied { execmod } for path="/system/bin/linker" dev="vda" ino=385 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0
12-20 18:49:13.353 12288-12288/? W/System: ClassLoader referenced unknown path: /data/app/com.whatsapp-1/base.apk
12-20 18:49:13.353 12288-12288/? W/System: ClassLoader referenced unknown path: /data/app/com.whatsapp-1/base.apk
12-20 18:49:13.353 12288-12288/? W/linker: Warning: unable to resolve "/data/app/com.whatsapp-1/base.apk": No such file or directory
12-20 18:49:13.353 12288-12288/? W/linker: Warning: unable to resolve "/data/app/com.whatsapp-1/base.apk": No such file or directory
12-20 18:49:13.353 12288-12288/? W/art: JIT profile information will not be recorded: profile file does not exits.
12-20 18:49:13.353 12288-12288/? W/asset: Asset path /data/app/com.whatsapp-1/base.apk is neither a directory nor file (type=1).
12-20 18:49:13.353 12288-12288/? D/AndroidRuntime: Shutting down VM
**12-20 18:49:13.354 12288-12288/? E/uncaught: android.content.res.Resources$NotFoundException: failed to add asset path /data/app/com.whatsapp-1/base.apk
                                                 at android.app.ResourcesManager.createAssetManager(ResourcesManager.java:253)
                                                 at android.app.ResourcesManager.createResourcesImpl(ResourcesManager.java:310)
                                                 at android.app.ResourcesManager.getOrCreateResources(ResourcesManager.java:571)
                                                 at android.app.ResourcesManager.getResources(ResourcesManager.java:645)
                                                 at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1846)
                                                 at android.app.LoadedApk.getResources(LoadedApk.java:766)
                                                 at android.app.ContextImpl.<init>(ContextImpl.java:2066)
                                                 at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:1870)
                                                 at android.app.ContextImpl.createPackageContext(ContextImpl.java:1855)
                                                 at com.lody.virtual.client.VClientImpl.createPackageContext(VClientImpl.java:450)
                                                 at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:269)
                                                 at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:206)
                                                 at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:120)
                                                 at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:73)
                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                 at android.os.Looper.loop(Looper.java:154)
                                                 at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)**
12-20 18:49:13.355 12288-12288/? I/art: System.exit called, status: 0
12-20 18:49:13.355 12288-12288/? I/AndroidRuntime: VM exiting with result code 0, cleanup skipped.
12-20 18:49:13.358 1623-2128/? I/ActivityManager: Process com.example.app:p0 (pid 12288) has died
12-20 18:49:13.358 1623-2128/? D/ActivityManager: cleanUpApplicationRecord -- 12288

Due to the update, Whatsapp is now installed under /data/app/com.whatsapp-2/base.apk, and not /data/app/com.whatsapp-1/base.apk, therefore VirtualApp unable to run the updated app.

中文:

1.安装WhatsApp（或任何其他应用程序）
2.使用VirtualApp克隆它
3.更新可用于WhatsApp，通过Play商店进行更新
4.尝试运行克隆

结果：克隆不会运行，停留在循环中。显示以上错误

由于更新，Whatsapp现在安装在/data/app/com.whatsapp-2/base.apk下，而不是/data/app/com.whatsapp-1/base.apk，因此VirtualApp无法运行更新的应用程序。

**Comment by xinyangslove** [comment]
请问你最后解决这个问题了么？

**Comment by qadirsuh** [comment]
I am getting the same for apps using google play services. like Daraz (pakistan), foodPanda etc
Anybody have a workaround?
