### ISSUE TITLE
cannot open `Sougou Input Method`

### ISSUE THREAD

**Issue by prife** [asLody/VirtualApp#44]
**crash log**
```
08-03 14:10:37.330 8041-8041/io.virtualapp:p3 I/View: ssignParent(ViewParent parent) parent is: null
08-03 14:10:37.340 8041-8041/io.virtualapp:p3 I/View: ssignParent(ViewParent parent) parent is: null
08-03 14:10:37.370 1554-1743/io.virtualapp I/MobclickAgent: Extend current session: F4F32A3857A88EBB425E9A36D1839BF4
08-03 14:10:37.770 8041-8041/io.virtualapp:p3 I/View: ssignParent(ViewParent parent) parent is: null
08-03 14:10:37.770 8041-8041/io.virtualapp:p3 I/View: ssignParent(ViewParent parent) parent is: null
08-03 14:10:38.210 1614-2203/io.virtualapp:x I/Process: Sending signal. PID: 8041 SIG: 9
08-03 14:10:38.280 1554-1554/io.virtualapp I/View: ssignParent(ViewParent parent) parent is: android.view.ViewRootImpl@316c836b
08-03 14:10:38.970 8163-8163/io.virtualapp:p3 I/HwCust: Constructor found for class android.app.HwCustApplicationPackageManagerImpl
08-03 14:10:39.350 8163-8163/io.virtualapp:p3 W/System.err: java.lang.NoSuchMethodException
08-03 14:10:39.350 8163-8163/io.virtualapp:p3 W/System.err:     at com.lody.virtual.helper.utils.Reflect.exactMethod(Reflect.java:399)
08-03 14:10:39.350 8163-8163/io.virtualapp:p3 W/System.err:     at com.lody.virtual.client.fixer.ContextFixer.fixCamera(ContextFixer.java:54)
08-03 14:10:39.350 8163-8163/io.virtualapp:p3 W/System.err:     at com.lody.virtual.client.core.AppSandBox.installLocked(AppSandBox.java:86)
08-03 14:10:39.350 8163-8163/io.virtualapp:p3 W/System.err:     at com.lody.virtual.client.core.AppSandBox.install(AppSandBox.java:61)
08-03 14:10:39.350 8163-8163/io.virtualapp:p3 W/System.err:     at com.lody.virtual.client.hook.patchs.am.HCallbackHook.handleLaunchActivity(HCallbackHook.java:126)
08-03 14:10:39.350 8163-8163/io.virtualapp:p3 W/System.err:     at com.lody.virtual.client.hook.patchs.am.HCallbackHook.handleMessage(HCallbackHook.java:91)
08-03 14:10:39.350 8163-8163/io.virtualapp:p3 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
08-03 14:10:39.350 8163-8163/io.virtualapp:p3 W/System.err:     at android.os.Looper.loop(Looper.java:135)
08-03 14:10:39.350 8163-8163/io.virtualapp:p3 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5538)
08-03 14:10:39.350 8163-8163/io.virtualapp:p3 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-03 14:10:39.350 8163-8163/io.virtualapp:p3 W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
08-03 14:10:39.350 8163-8163/io.virtualapp:p3 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:958)
08-03 14:10:39.350 8163-8163/io.virtualapp:p3 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:753)
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/renderscript/RenderScriptCacheDir;
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err:     at com.lody.virtual.client.core.AppSandBox.setupRuntime(AppSandBox.java:183)
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err:     at com.lody.virtual.client.core.AppSandBox.installLocked(AppSandBox.java:100)
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err:     at com.lody.virtual.client.core.AppSandBox.install(AppSandBox.java:61)
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err:     at com.lody.virtual.client.hook.patchs.am.HCallbackHook.handleLaunchActivity(HCallbackHook.java:126)
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err:     at com.lody.virtual.client.hook.patchs.am.HCallbackHook.handleMessage(HCallbackHook.java:91)
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err:     at android.os.Looper.loop(Looper.java:135)
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5538)
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:958)
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:753)
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.renderscript.RenderScriptCacheDir" on path: DexPathList[[zip file "/data/app/io.virtualapp-1/base.apk"],nativeLibraryDirectories=[/data/app/io.virtualapp-1/lib/arm, /vendor/lib, /system/lib]]
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err: 	... 12 more
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err: 	Suppressed: java.lang.ClassNotFoundException: android.renderscript.RenderScriptCacheDir
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err:     at java.lang.Class.classForName(Native Method)
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err: 		... 13 more
08-03 14:10:39.390 8163-8163/io.virtualapp:p3 W/System.err: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
08-03 14:10:39.400 8163-8163/io.virtualapp:p3 I/MultiDex: VM with version 2.1.0 has multidex support
08-03 14:10:39.400 8163-8163/io.virtualapp:p3 I/MultiDex: install
08-03 14:10:39.400 8163-8163/io.virtualapp:p3 I/MultiDex: VM has multidex support, MultiDex support library is disabled.
08-03 14:10:39.610 8163-8163/io.virtualapp:p3 W/ResourceType: ResTable_typeSpec entry count inconsistent: given 1, previously 1445
08-03 14:10:39.610 8163-8163/io.virtualapp:p3 W/ResourceType: ResTable_typeSpec entry count inconsistent: given 1, previously 1445
08-03 14:10:39.670 8163-8163/io.virtualapp:p3 I/View: ssignParent(ViewParent parent) parent is: android.view.ViewRootImpl@1543ac57
08-03 14:10:39.750 8163-8163/io.virtualapp:p3 I/View: ssignParent(ViewParent parent) parent is: android.view.ViewRootImpl@30256a9d
08-03 14:10:39.790 8163-8192/io.virtualapp:p3 I/OpenGLRenderer: Initialized EGL, version 1.4
08-03 14:10:40.660 1554-1554/io.virtualapp I/View: ssignParent(ViewParent parent) parent is: null
08-03 14:10:40.670 1554-1554/io.virtualapp I/View: ssignParent(ViewParent parent) parent is: null
```

![screenshot_2016-08-03-14-08-09](https://cloud.githubusercontent.com/assets/1572684/17355591/347b4e78-5984-11e6-8feb-1e559c589381.png)

**Comment by prife** [comment]
More details:
- HW: Huawei P8
- ROM: Android 5.0.1 with EMUI 3.1

**Comment by asLody** [comment]
Invalid issue.
