### ISSUE TITLE
我的红包插件打不开

### ISSUE THREAD

**Issue by qssq** [asLody/VirtualApp#442]
at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:336)
                                                 at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:199)
                                                 at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:120)
                                                 at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:73)
                                                 at android.os.Handler.dispatchMessage(Handler.java:101)
                                                 at android.os.Looper.loop(Looper.java:156)
                                                 at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by qssq** [comment]
01-08 14:27:35.567 446-446/? E/ServiceManager: try to find service failed, not allowed access from isolated processes.
01-08 14:27:36.100 2301-2301/? E/HwStepCounter: dealReportData tm: 2018-01-08 14:27:37 steps_value[0] : 0 state_value[0]:0 level_value[0]:0
01-08 14:27:36.567 446-446/? E/ServiceManager: try to find service failed, not allowed access from isolated processes.
01-08 14:27:37.070 447-1365/? E/ion: set flags ioctrl failed!
01-08 14:27:37.073 447-1365/? E/ion: set flags ioctrl failed!
01-08 14:27:37.075 447-1365/? E/ion: set flags ioctrl failed!
01-08 14:27:37.120 1228-5161/? E/Process: isHighLoadProcess: get cpu failed
01-08 14:27:37.139 1228-2695/? E/HsmCoreServiceImpl: onTransact in code is: 103
01-08 14:27:37.325 1228-1379/? E/WifiConfigManager: updateConfiguration freq=2457 BSSID=d4:ee:07:0c:56:62 RSSI=-25 "huluboshi_jiluyou"WPA_PSK
01-08 14:27:37.342 1228-2874/? E/Process: isHighLoadProcess: get cpu failed
01-08 14:27:37.415 1228-1379/? E/WifiConfigManager: updateConfiguration freq=2457 BSSID=d4:ee:07:0c:56:62 RSSI=-26 "huluboshi_jiluyou"WPA_PSK
01-08 14:27:37.433 28546-28546/? E/uncaught: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                                                 at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:336)
                                                 at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:199)
                                                 at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:120)
                                                 at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:73)
                                                 at android.os.Handler.dispatchMessage(Handler.java:101)
                                                 at android.os.Looper.loop(Looper.java:156)
                                                 at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
01-08 14:27:37.450 1228-2875/? E/HsmCoreServiceImpl: onTransact in code is: 103
01-08 14:27:37.458 1228-2876/? E/HsmCoreServiceImpl: onTransact in code is: 102
01-08 14:27:37.458 1228-2877/? E/HsmCoreServiceImpl: onTransact in code is: 102
01-08 14:27:37.486 1228-5163/? E/Process: isHighLoadProcess: get cpu failed
01-08 14:27:37.568 446-446/? E/ServiceManager: try to find service failed, not allowed access from isolated processes.
01-08 14:27:37.622 1228-5163/? E/Process: isHighLoadProcess: get cpu failed
01-08 14:27:37.725 28570-28570/? E/uncaught: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                                                 at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:336)
                                                 at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:199)
                                                 at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:120)
                                                 at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:73)
                                                 at android.os.Handler.dispatchMessage(Handler.java:101)
                                                 at android.os.Looper.loop(Looper.java:156)
                                                 at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
01-08 14:27:37.796 1228-2877/? E/HsmCoreServiceImpl: onTransact in code is: 102
01-08 14:27:37.796 1228-2876/? E/HsmCoreServiceImpl: onTransact in code is: 102
01-08 14:27:37.821 1228-2880/? E/Process: isHighLoadProcess: get cpu failed
01-08 14:27:37.836 1228-1240/? E/Process: isHighLoadProcess: get cpu failed
01-08 14:27:37.969 1228-5163/? E/Process: isHighLoadProcess: get cpu failed
01-08 14:27:37.991 28588-28588/? A/libc: Fatal signal 4 (SIGILL), code 1, fault addr 0xed1d3906 in tid 28588 (com.tencent.red)
                                         
                                         [ 01-08 14:27:37.991   422:  422 W/         ]
                                         debuggerd: handling request: pid=28588 uid=10338 gid=10338 tid=28588
01-08 14:27:38.064 28604-28604/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-08 14:27:38.064 28604-28604/? A/DEBUG: Build fingerprint: 'honor/FRD-AL10/HWFRD:7.0/HUAWEIFRD-AL10/C00B395:user/release-keys'
01-08 14:27:38.064 28604-28604/? A/DEBUG: Revision: '0'
01-08 14:27:38.064 28604-28604/? A/DEBUG: ABI: 'arm'
01-08 14:27:38.064 28604-28604/? A/DEBUG: pid: 28588, tid: 28588, name: com.tencent.red  >>> com.tencent.red <<<
01-08 14:27:38.064 28604-28604/? A/DEBUG: signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0xed1d3906
01-08 14:27:38.064 28604-28604/? A/DEBUG:     r0 ff808d59  r1 00000000  r2 00000000  r3 e90e0ad9
01-08 14:27:38.064 28604-28604/? A/DEBUG:     r4 e90e0ad9  r5 00000000  r6 60000000  r7 ff808d58
01-08 14:27:38.064 28604-28604/? A/DEBUG:     r8 00000018  r9 ff808e24  sl 00000001  fp ff808da0
01-08 14:27:38.064 28604-28604/? A/DEBUG:     ip e910b8a8  sp ff808d40  lr ed2f4c39  pc ed1d3906  cpsr 800d0030
01-08 14:27:38.065 28604-28604/? A/DEBUG: backtrace:
01-08 14:27:38.065 28604-28604/? A/DEBUG:     #00 pc 00000906  <anonymous:ed1d3000>
01-08 14:27:38.065 28604-28604/? A/DEBUG:     #01 pc 00002c35  /system/bin/linker (__dl__ZL10dlopen_extPKciPK17android_dlextinfoPv+28)
01-08 14:27:38.066 28604-28604/? A/DEBUG:     #02 pc 00015ad5  /data/app/io.va.exposed-2/lib/arm/libva++.so (_Z19getDvmOrArtSOHandlev+56)
01-08 14:27:38.066 28604-28604/? A/DEBUG:     #03 pc 000157b3  /data/app/io.va.exposed-2/lib/arm/libva++.so (_Z13hookAndroidVMN8facebook3jni11JArrayClassIP8_jobjectEEP8_jstringhii+114)
01-08 14:27:38.066 28604-28604/? A/DEBUG:     #04 pc 000138c5  /data/app/io.va.exposed-2/lib/arm/libva++.so
01-08 14:27:38.066 28604-28604/? A/DEBUG:     #05 pc 0060e4eb  /data/app/io.va.exposed-2/oat/arm/base.odex (offset 0x5ca000)
01-08 14:27:38.102 1228-1436/? E/HwCHRWebMonitor: WebMonitor [mNetWorkIsSuck=0 mUIDIsSuck=]  WebSpeed [WEBSENDSEGS=2  WEBRESENDSEGS=1  WEBRECVSEGS=1  WEBERRSEGS=0  WEBOUTRSTS=0  WEBESTABLISRST=0  WEBRTTDURATION=0  WEBRTTSEGS=0  WEBSRTT=130  WEBSNDDUPACKS=0  SENDSEGS=0  RESENDSEGS=0  RECVSEGS=0  ERRSEGS=0  OUTRSTS=0  ESTABLISRST=0  RTTDURATION=0  RTTSEGS=0  SNDDUPACKS=0  suckTimes=0 recovage_times=0]
01-08 14:27:38.102 1228-1436/? E/HwCHRWifiRSSIGroupSummery: updateTcpSummery mRSSI:-27  HwCHRWifiRSSIGroup [rssi_index=4, rtt_tcp_packets=5074, rtt_tcp_duration=277966, rtt_lan_duration=15013, rtt_lan_failures=0, rtt_lan_succ=271, rtt_lan_max=952, rtt_lan_min=2,same_area_frequency=0,adjacent_area_frequency=0]
01-08 14:27:38.108 1228-1436/? E/HwCHRWebMonitor: HwCHRWifiPacketCnt [mTXGood=6, mTXbad=0, mRXGood=1] rssi=-27
01-08 14:27:38.109 1228-1436/? E/HwCHRWebMonitor: running processName=io.va.exposed:p4
01-08 14:27:38.110 1228-1436/? E/HwCHRWebMonitor: HwCHRWifiUIDWebSpeed [appName=com.tencent.mobileqq UID=10395  WEBSENDSEGS=0  WEBRESENDSEGS=0  WEBRECVSEGS=1  WEBERRSEGS=0  WEBOUTRSTS=0  WEBESTABLISRST=0  WEBRTTDURATION=0  WEBRTTSEGS=0  WEBSNDDUPACKS=0  suckTimes=0 recovage_times=0]
01-08 14:27:38.217 1228-2701/? E/HsmCoreServiceImpl: onTransact in code is: 102
01-08 14:27:38.217 1228-2695/? E/HsmCoreServiceImpl: onTransact in code is: 102
01-08 14:27:38.220 1228-1372/? E/Process: isHighLoadProcess: get cpu failed
01-08 14:27:38.227 1228-1372/? E/Process: isHighLoadProcess: get cpu failed
01-08 14:27:38.253 577-577/? E/Thermal-daemon: [pa_0] temp_new :34  temp_old :33
01-08 14:27:38.253 577-577/? E/Thermal-daemon: Report temperature: [pa_0] temp :34  report_threshold:1
01-08 14:27:38.282 593-1124/? E/logserver: imonitor_add_dynamic_path, path:/data/system/dropbox/SYSTEM_TOMBSTONE@1515392858182.txt.gz
01-08 14:27:38.818 446-446/? E/ServiceManager: try to find service failed, not allowed access from isolated processes.
