### ISSUE TITLE
Android Oreo (8.0): Whatsapp not launch correctly.

### ISSUE THREAD

**Issue by code4rox** [asLody/VirtualApp#505]
When I open Whatsapp in Android Oreo (8.0) its not launch correctly , after clone this give me following errors in `com.whatsapp debug package`  

```
06-03 14:04:29.486 12971-12971/com.whatsapp E/NativeEngine: java.lang.RuntimeException: Unable to find the so.
        at com.lody.virtual.client.NativeEngine.enableIORedirect(NativeEngine.java:129)
        at com.lody.virtual.client.VClientImpl.startIOUniformer(VClientImpl.java:431)
        at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:264)
        at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:206)
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:120)
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:73)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

```

06-04 11:55:23.069 17704-17704/com.whatsapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.whatsapp, PID: 17704
    java.lang.RuntimeException: Unable to create application com.whatsapp.AppShell: java.lang.SecurityException: Calling uid 10533 gave package com.whatsapp which is owned by uid 10217
        at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:344)
        at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:206)
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:120)
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:73)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.SecurityException: Calling uid 10533 gave package com.whatsapp which is owned by uid 10217
        at android.os.Parcel.readException(Parcel.java:1942)
        at android.os.Parcel.readException(Parcel.java:1888)
        at android.app.INotificationManager$Stub$Proxy.createNotificationChannelGroups(INotificationManager.java:1456)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.lody.virtual.client.hook.base.MethodInvocationStub$HookInvocationHandler.invoke(MethodInvocationStub.java:189)
        at java.lang.reflect.Proxy.invoke(Proxy.java:913)
        at $Proxy9.createNotificationChannelGroups(Unknown Source)
        at android.app.NotificationManager.createNotificationChannelGroups(NotificationManager.java:410)
        at android.app.NotificationManager.createNotificationChannelGroup(NotificationManager.java:399)
        at com.whatsapp.notification.ai.a(:250504)
        at com.whatsapp.v.a(:310685)
        at com.whatsapp.App.a(:107732)
        at com.facebook.b.a.a.a.c.onCreate(:65614)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1129)
        at com.lody.virtual.client.hook.delegate.InstrumentationDelegate.callApplicationOnCreate(InstrumentationDelegate.java:225)
        at com.lody.virtual.client.hook.delegate.AppInstrumentation.callApplicationOnCreate(AppInstrumentation.java:149)
        at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:331)
        at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:206) 
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:120) 
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:73) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6798) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

In **`io.virtualapp:x`** debug package

```
06-04 11:50:33.978 13002-13002/io.virtualapp:x E/ActivityThread: Service com.lody.virtual.client.stub.StubJob has leaked ServiceConnection com.lody.virtual.client.stub.StubJob$JobSession@586229e that was originally bound here
    android.app.ServiceConnectionLeaked: Service com.lody.virtual.client.stub.StubJob has leaked ServiceConnection com.lody.virtual.client.stub.StubJob$JobSession@586229e that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1565)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1457)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1606)
        at android.app.ContextImpl.bindService(ContextImpl.java:1558)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:679)
        at com.lody.virtual.client.stub.StubJob$1.startJob(StubJob.java:73)
        at android.app.job.IJobService$Stub.onTransact(IJobService.java:61)
        at android.os.Binder.execTransact(Binder.java:692)
```

**Comment by 24Lathiya** [comment]
@code4rox  is there any update ?? My app throwing "com.lody.virtual.client.env.DeadServerException: android.os.DeadObjectException". How you fix that ? pls help.

**Comment by 24Lathiya** [comment]
@code4rox  how you get list of application in ListAppFragment for Orea ?

**Comment by danglam95** [comment]
There is no way to handle this error ?

**Comment by niyingxunzong** [comment]
@24Lathiya 我认为这个异常是由很多情况引起的，如果有某个error 导致了 VA 的 :x 进程崩溃，那么你再调用VA服务的时候就会出现这个异常。

**Comment by niyingxunzong** [comment]
@code4rox @danglam95  这个错误是因为 whatsapp 使用了Android 8.0 的新特性，Android 8.0 添加了NotificationChannel 的功能，而目前的VA的版本并没有支持8.0 上 Notification 的新特性，只要添加几个Hook点就能解决了。我对这个错误做了简单修复，具体可见[我的github](https://github.com/niyingxunzong/VirtualApp/commits/master)

**Comment by lynn-long** [comment]
@code4rox @24Lathiya @niyingxunzong 
Try to change the death judgment of the remote process to 
`public static boolean isBinderDead(IInterface ibinder){
         Return (ibinder == null)
                 || (!ibinder.asBinder().isBinderAlive())
                 || (!ibinder.asBinder().pingBinder());
     }`
It will work very well

**Comment by lhwalq** [comment]
> @code4rox @24Lathiya @niyingxunzong
> Try to change the death judgment of the remote process to
> `public static boolean isBinderDead(IInterface ibinder){          Return (ibinder == null)                  || (!ibinder.asBinder().isBinderAlive())                  || (!ibinder.asBinder().pingBinder());      }`
> It will work very well

Can you tell me where this method is added?

**Comment by niyingxunzong** [comment]
> > @code4rox @24Lathiya @niyingxunzong
> > Try to change the death judgment of the remote process to
> > `public static boolean isBinderDead(IInterface ibinder){          Return (ibinder == null)                  || (!ibinder.asBinder().isBinderAlive())                  || (!ibinder.asBinder().pingBinder());      }`
> > It will work very well
> 
> Can you tell me where this method is added?

这种方式不适合你，这个是解决服务进程死后如何自动重启的。我刚才看了下whatsapp，的崩溃，是因为8.0的新特性引起的。[新特性描述](https://blog.csdn.net/weixin_37077539/article/details/80067073)，我简单修复了一下，你可以试试

**Comment by lhwalq** [comment]
> > > @code4rox @24Lathiya @niyingxunzong
> > > Try to change the death judgment of the remote process to
> > > `public static boolean isBinderDead(IInterface ibinder){          Return (ibinder == null)                  || (!ibinder.asBinder().isBinderAlive())                  || (!ibinder.asBinder().pingBinder());      }`
> > > It will work very well
> > 
> > 
> > Can you tell me where this method is added?
> 
> 这种方式不适合你，这个是解决服务进程死后如何自动重启的。我刚才看了下whatsapp，的崩溃，是因为8.0的新特性引起的。[新特性描述](https://blog.csdn.net/weixin_37077539/article/details/80067073)，我简单修复了一下，你可以试试

ok，非常感谢
