### ISSUE TITLE
还有很多app都兼容不了

### ISSUE THREAD

**Issue by chaopengTan** [asLody/VirtualApp#524]
[图片] ，放在手机里面是可以正常运行的，但是到va里面的话，很多都不兼容
  最新版的商业版

**Comment by chaopengTan** [comment]
No implementation found for void com.lody.virtual.client.NativeEngine.nativeIOForbid(java.lang.String) (tried Java_com_lody_virtual_client_NativeEngine_nativeIOForbid and Java_com_lody_virtual_client_NativeEngine_nativeIOForbid__Ljava_lang_String_2)
09-30 16:44:14.871 30348-30348/com.racergame.cityracing3d E/NativeEngine: java.lang.UnsatisfiedLinkError: No implementation found for void com.lody.virtual.client.NativeEngine.nativeIOForbid(java.lang.String) (tried Java_com_lody_virtual_client_NativeEngine_nativeIOForbid and Java_com_lody_virtual_client_NativeEngine_nativeIOForbid__Ljava_lang_String_2)
        at com.lody.virtual.client.NativeEngine.nativeIOForbid(Native Method)
        at com.lody.virtual.client.NativeEngine.forbid(NativeEngine.java:163)
        at com.lody.virtual.client.VClient.forbidHost(VClient.java:663)
        at com.lody.virtual.client.VClient.startIORelocater(VClient.java:608)
        at com.lody.virtual.client.VClient.bindApplicationNoCheck(VClient.java:388)
        at com.lody.virtual.client.VClient.bindApplication(VClient.java:299)
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:151)
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:79)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
