### ISSUE TITLE
android

### ISSUE THREAD

**Issue by lhwalq** [asLody/VirtualApp#541]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.twitter.android-2/base.apk", zip file "/data/app/com.twitter.android-2/base.apk"],nativeLibraryDirectories=[/data/user/0/jiubang.commerce.gomultiple.info.cloneapp.mochat.in.goast/virtual/data/app/com.twitter.android/lib, /data/app/com.twitter.android-2/base.apk!/lib/armeabi-v7a, /data/app/com.twitter.android-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libcrashlytics.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:984)
        at java.lang.System.loadLibrary(System.java:1562)
        at com.crashlytics.android.ndk.JniNativeApi.<clinit>(Twttr:13)
        at com.crashlytics.android.ndk.c.a_(Twttr:50)
        at io.fabric.sdk.android.g.a(Twttr:44)
        at io.fabric.sdk.android.services.concurrency.AsyncTask.a(Twttr:611)
        at io.fabric.sdk.android.services.concurrency.c.a(Twttr:43)
        at io.fabric.sdk.android.h.p(Twttr:69)
        at io.fabric.sdk.android.c.a(Twttr:466)
        at io.fabric.sdk.android.c.i(Twttr:410)
        at io.fabric.sdk.android.c.d(Twttr:368)
        at io.fabric.sdk.android.c.a(Twttr:359)
        at com.twitter.fabric.a.a(Twttr:37)
        at com.twitter.app.TwitterApplication.onCreate(Twttr:60)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
        at com.lody.virtual.client.hook.delegate.InstrumentationDelegate.callApplicationOnCreate(InstrumentationDelegate.java:225)
        at com.lody.virtual.client.hook.delegate.AppInstrumentation.callApplicationOnCreate(AppInstrumentation.java:149)
        at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:331)
        at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:206)
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:143)
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:92)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6121)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by lhwalq** [comment]
@asLody

**Comment by lhwalq** [comment]
@code4rox
