### ISSUE TITLE
Can't Add App Android 9

### ISSUE THREAD

**Issue by beryindo** [asLody/VirtualApp#554]
Hai, I use mi 8 lite, running on android 9, why I can't add app on virtualapp ? please help. thank you

**Comment by yuzhongrong** [comment]
me to  the same problem

**Comment by yuzhongrong** [comment]
2019-10-28 01:08:58.854 13892-14254/? W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object mirror.RefStaticMethod.callWithException(java.lang.Object[])' on a null object reference
2019-10-28 01:08:58.854 13892-14254/? W/System.err:     at com.lody.virtual.helper.compat.PackageParserCompat.collectCertificates(PackageParserCompat.java:174)
2019-10-28 01:08:58.855 13892-14254/? W/System.err:     at com.lody.virtual.server.pm.parser.PackageParserEx.parsePackage(PackageParserEx.java:60)
2019-10-28 01:08:58.855 13892-14254/? W/System.err:     at com.lody.virtual.server.pm.VAppManagerService.installPackage(VAppManagerService.java:157)
2019-10-28 01:08:58.855 13892-14254/? W/System.err:     at com.lody.virtual.server.pm.VAppManagerService.installPackage(VAppManagerService.java:143)
2019-10-28 01:08:58.855 13892-14254/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-10-28 01:08:58.855 13892-14254/? W/System.err:     at com.lody.virtual.helper.ipcbus.IPCMethod.handleTransact(IPCMethod.java:68)
2019-10-28 01:08:58.855 13892-14254/? W/System.err:     at com.lody.virtual.helper.ipcbus.TransformBinder.onTransact(TransformBinder.java:30)
2019-10-28 01:08:58.855 13892-14254/? W/System.err:     at android.os.Binder.execTransact(Binder.java:739)

**Comment by yuzhongrong** [comment]
in android 9.0 with huawei

**Comment by papmodern** [comment]
Same problem here !

**Comment by kiceargy** [comment]
On Android 9 some api is hide from Reflection. For bypass this use FreeReflection library by weishu,
Also, necessary new proxy for handleLaunchActivity

**Comment by w0x12e** [comment]
Same problem here !
