### ISSUE TITLE
Failed to verify signature: no verified SignerInfos (微信安装失败)

### ISSUE THREAD

**Issue by hermitsgame** [asLody/VirtualApp#569]
2020-05-05 10:08:02.021 16484-16500/io.virtualapp:x W/System.err: android.content.pm.PackageParser$PackageParserException: Failed to collect certificates from /data/app/com.tencent.mm-qDt-tgpyLv06YIiwXo4GBA==/base.apk
2020-05-05 10:08:02.022 16484-16500/io.virtualapp:x W/System.err:     at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1687)
2020-05-05 10:08:02.022 16484-16500/io.virtualapp:x W/System.err:     at android.content.pm.PackageParser.collectCertificatesInternal(PackageParser.java:1536)
2020-05-05 10:08:02.022 16484-16500/io.virtualapp:x W/System.err:     at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1518)
2020-05-05 10:08:02.022 16484-16500/io.virtualapp:x W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-05-05 10:08:02.022 16484-16500/io.virtualapp:x W/System.err:     at mirror.RefStaticMethod.callWithException(RefStaticMethod.java:128)
2020-05-05 10:08:02.022 16484-16500/io.virtualapp:x W/System.err:     at com.lody.virtual.helper.compat.PackageParserCompat.collectCertificates(PackageParserCompat.java:174)
2020-05-05 10:08:02.022 16484-16500/io.virtualapp:x W/System.err:     at com.lody.virtual.server.pm.parser.PackageParserEx.parsePackage(PackageParserEx.java:60)
2020-05-05 10:08:02.023 16484-16500/io.virtualapp:x W/System.err:     at com.lody.virtual.server.pm.VAppManagerService.installPackage(VAppManagerService.java:157)
2020-05-05 10:08:02.023 16484-16500/io.virtualapp:x W/System.err:     at com.lody.virtual.server.pm.VAppManagerService.installPackage(VAppManagerService.java:143)
2020-05-05 10:08:02.023 16484-16500/io.virtualapp:x W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-05-05 10:08:02.023 16484-16500/io.virtualapp:x W/System.err:     at com.lody.virtual.helper.ipcbus.IPCMethod.handleTransact(IPCMethod.java:68)
2020-05-05 10:08:02.023 16484-16500/io.virtualapp:x W/System.err:     at com.lody.virtual.helper.ipcbus.TransformBinder.onTransact(TransformBinder.java:30)
2020-05-05 10:08:02.023 16484-16500/io.virtualapp:x W/System.err:     at android.os.Binder.execTransact(Binder.java:697)
2020-05-05 10:08:02.023 16484-16500/io.virtualapp:x W/System.err: Caused by: java.lang.SecurityException: /data/app/com.tencent.mm-qDt-tgpyLv06YIiwXo4GBA==/base.apk failed verification of META-INF/CERT.SF
2020-05-05 10:08:02.023 16484-16500/io.virtualapp:x W/System.err:     at android.util.jar.StrictJarVerifier.failedVerification(StrictJarVerifier.java:157)
2020-05-05 10:08:02.024 16484-16500/io.virtualapp:x W/System.err:     at android.util.jar.StrictJarVerifier.verifyCertificate(StrictJarVerifier.java:363)
2020-05-05 10:08:02.024 16484-16500/io.virtualapp:x W/System.err:     at android.util.jar.StrictJarVerifier.readCertificates(StrictJarVerifier.java:288)
2020-05-05 10:08:02.024 16484-16500/io.virtualapp:x W/System.err:     at android.util.jar.StrictJarFile.<init>(StrictJarFile.java:128)
2020-05-05 10:08:02.024 16484-16500/io.virtualapp:x W/System.err:     at android.util.jar.StrictJarFile.<init>(StrictJarFile.java:86)
2020-05-05 10:08:02.024 16484-16500/io.virtualapp:x W/System.err:     at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1615)
2020-05-05 10:08:02.024 16484-16500/io.virtualapp:x W/System.err: 	... 12 more
2020-05-05 10:08:02.024 16484-16500/io.virtualapp:x W/System.err: Caused by: java.security.GeneralSecurityException: Failed to verify signature: no verified SignerInfos
2020-05-05 10:08:02.024 16484-16500/io.virtualapp:x W/System.err:     at android.util.jar.StrictJarVerifier.verifyBytes(StrictJarVerifier.java:311)
2020-05-05 10:08:02.025 16484-16500/io.virtualapp:x W/System.err:     at android.util.jar.StrictJarVerifier.verifyCertificate(StrictJarVerifier.java:358)
2020-05-05 10:08:02.025 16484-16500/io.virtualapp:x W/System.err: 	... 16 more

**Comment by dingyong666** [comment]
这个项目现在已经废弃了，想用得花50w买新版本

**Comment by hermitsgame** [comment]
@dingyong666 这么贵？
