### ISSUE TITLE
android.os.DeadObjectException in android 10.0

### ISSUE THREAD

**Issue by neerajsublimearchs** [asLody/VirtualApp#577]
Hi,

I and getting the android.os.DeadObjectException in android 10.0 while fetching the installed apps from the device.
I tried a lot to fix this issue but couldn't find any solution for this. 

I am getting this issue in IPCMethod.java at the line code: 
server.transact(code, data, reply, 0);

Following are the log report that I am getting at my end:
2020-09-25 23:57:27.211 21508-21787/io.virtualapp W/System.err: android.os.DeadObjectException
2020-09-25 23:57:27.211 21508-21787/io.virtualapp W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
2020-09-25 23:57:27.211 21508-21787/io.virtualapp W/System.err:     at android.os.BinderProxy.transact(BinderProxy.java:558)
2020-09-25 23:57:27.211 21508-21787/io.virtualapp W/System.err:     at com.lody.virtual.helper.ipcbus.IPCMethod.callRemote(IPCMethod.java:110)
2020-09-25 23:57:27.211 21508-21787/io.virtualapp W/System.err:     at com.lody.virtual.helper.ipcbus.IPCInvocationBridge.invoke(IPCInvocationBridge.java:27)
2020-09-25 23:57:27.211 21508-21787/io.virtualapp W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
2020-09-25 23:57:27.211 21508-21787/io.virtualapp W/System.err:     at $Proxy2.getInstalledAppInfo(Unknown Source)
2020-09-25 23:57:27.211 21508-21787/io.virtualapp W/System.err:     at com.lody.virtual.client.core.VirtualCore.getInstalledAppInfo(VirtualCore.java:520)
2020-09-25 23:57:27.211 21508-21787/io.virtualapp W/System.err:     at io.virtualapp.home.repo.AppRepository.convertPackageInfoToAppData(AppRepository.java:147)
2020-09-25 23:57:27.211 21508-21787/io.virtualapp W/System.err:     at io.virtualapp.home.repo.AppRepository.lambda$getInstalledApps$1(AppRepository.java:85)
2020-09-25 23:57:27.211 21508-21787/io.virtualapp W/System.err:     at io.virtualapp.home.repo.-$$Lambda$AppRepository$9ougTewtyti8LsqxMaw1O9BH6Uo.call(Unknown Source:4)
2020-09-25 23:57:27.211 21508-21787/io.virtualapp W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-09-25 23:57:27.212 21508-21787/io.virtualapp W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
2020-09-25 23:57:27.212 21508-21787/io.virtualapp W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-09-25 23:57:27.212 21508-21787/io.virtualapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-09-25 23:57:27.212 21508-21787/io.virtualapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-09-25 23:57:27.212 21508-21787/io.virtualapp W/System.err:     at java.lang.Thread.run(Thread.java:919)

I have attached the issue in the attachment as well. The issue is basically in the android 10.0 or greater than Android 8.0. Other devices does have the flawless functions. 

Is there anyone who have the same and got any success in it.

Many thanks!

**Comment by peter196** [comment]
me too!
