### ISSUE TITLE
gms 目前不支持game组件

### ISSUE THREAD

**Issue by wanjin23** [asLody/VirtualApp#61]
com.google.android.play.games 没有加载起来，会导致需要game组件的地方崩溃

**Comment by wanjin23** [comment]
崩溃日志：

                                                                         java.lang.IllegalStateException: Only Play Games can use this package!
                                                                             at com.google.android.gms.common.internal.Asserts.fail(Asserts.java:135)
                                                                             at com.google.android.gms.games.service.PlayGames1pServiceBroker.onGetService(PlayGames1pServiceBroker.java:92)
                                                                             at com.google.android.gms.common.internal.AbstractServiceBroker.getService(AbstractServiceBroker.java:573)
                                                                             at com.google.android.gms.common.internal.GmsClient.getRemoteService(GmsClient.java:1289)
                                                                             at com.google.android.gms.common.api.internal.GoogleApiClientConnecting$GetRemoteServiceTask.runLocked(GoogleApiClientConnecting.java:784)
                                                                             at com.google.android.gms.common.api.internal.GoogleApiClientConnecting$WorkerThreadTask.run(GoogleApiClientConnecting.java:709)
                                                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                             at com.google.android.gms.common.util.concurrent.PriorityRunnable.run(PriorityRunnable.java:17)
                                                                             at java.lang.Thread.run(Thread.java:831)
