### ISSUE TITLE
打开墨迹天气有问题，log如下：

### ISSUE THREAD

**Issue by sunpengshuai** [asLody/VirtualApp#83]
分析应该是友盟读写数据库，使用的是自定义的路径导致。具体log日志如下，友盟是最新的版本v6.0.1.
Failed to open database '/data/data/com.moji.mjweather/databases/cc/cc.db'.
                                                                  android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
                                                                      at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
                                                                      at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:207)
                                                                      at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:191)
                                                                      at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                                      at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                                      at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                      at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
                                                                      at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
                                                                      at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                                                                      at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:717)
                                                                      at u.aly.e.openOrCreateDatabase(UMCCPathDatabaseContext.java:44)
                                                                      at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
                                                                      at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                                      at u.aly.dw.b(UMCCDBHelper.java:56)
                                                                      at u.aly.dw.<init>(UMCCDBHelper.java:51)
                                                                      at u.aly.dw.<init>(UMCCDBHelper.java:46)
                                                                      at u.aly.dw.<init>(UMCCDBHelper.java:18)
                                                                      at u.aly.dw$a.<clinit>(UMCCDBHelper.java:24)
                                                                      at u.aly.dw.a(UMCCDBHelper.java:30)
                                                                      at u.aly.b.b(DatabaseManager.java:27)
                                                                      at u.aly.b.a(DatabaseManager.java:33)
                                                                      at u.aly.o.a(UMCCStorageManager.java:58)
                                                                      at u.aly.ei.a(UMCCAggregatedManager.java:157)
                                                                      at com.umeng.analytics.g.run(SafeRunnable.java:8)
                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                      at java.lang.Thread.run(Thread.java:818)
08-29 16:27:15.123 29138-29287/io.virtualapp:p9 E/SQLiteLog: (14) cannot open file at line 31278 of [2ef4f3a5b1]
08-29 16:27:15.123 29138-29287/io.virtualapp:p9 E/SQLiteLog: (14) os_unix.c:31278: (2) open(/data/data/com.moji.mjweather/databases/cc/cc.db) -

**Comment by cqllang** [comment]
同样的问题，
加载带有友盟SDK的app时，遇到问题的
友盟6.0.1sdk代码：
public static String a(Context paramContext)
{
return "/data/data/" + paramContext.getPackageName() + "/databases/cc/";
}
