### ISSUE TITLE
打开今日头条，图片加载不出来，报的错是 java.lang.UnsatisfiedLinkError，log如下

### ISSUE THREAD

**Issue by yuhuayi** [asLody/VirtualApp#84]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/io.virtualapp-1/base.apk"],nativeLibraryDirectories=[/data/app/io.virtualapp-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libiohook.so"
                                                                   at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                   at java.lang.System.loadLibrary(System.java:989)
                                                                   at com.lody.virtual.IOHook.<clinit>(IOHook.java:42)
                                                                   at com.lody.virtual.client.VClientImpl.handleBindApplication(VClientImpl.java:175)
                                                                   at com.lody.virtual.client.VClientImpl.access$100(VClientImpl.java:45)
                                                                   at com.lody.virtual.client.VClientImpl$H.handleMessage(VClientImpl.java:138)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                   at android.os.Looper.loop(Looper.java:194)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by yuhuayi** [comment]
我的问题，不好意思
