### ISSUE TITLE
最新代码Facebook添加后无法启动

### ISSUE THREAD

**Issue by piersguo** [asLody/VirtualApp#89]
我记得之前8月17号的版本是可以的，后面好像就不行了，出错log如下:

09-01 15:17:26.852 15788-15788/io.virtualapp:p9 D/AndroidRuntime: Shutting down VM
09-01 15:17:26.853 15788-15788/io.virtualapp:p9 E/art: invalid stream - problem with parameter iterator in /data/app/com.facebook.katana-1/base.apk:classes2.dex for method java.lang.Object com.google.common.cache.LocalCache$Segment.a(com.google.common.cache.LocalCache$Segment, java.lang.Object, int, com.google.common.cache.LocalCache$LoadingValueReference, com.google.common.cache.CacheLoader)
09-01 15:17:26.853 15788-15788/io.virtualapp:p9 E/art: invalid stream - problem with parameter iterator in /data/app/com.facebook.katana-1/base.apk:classes2.dex for method java.lang.Object com.google.common.cache.LocalCache$Segment.b(com.google.common.cache.LocalCache$Segment, java.lang.Object, int, com.google.common.cache.CacheLoader)
09-01 15:17:26.853 15788-15788/io.virtualapp:p9 E/VClientImpl: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.facebook.katana/com.facebook.katana.activity.FbMainTabActivity}: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.UnsupportedOperationException: Injector is not supported in process io.virtualapp:p9
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                   at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.UnsupportedOperationException: Injector is not supported in process io.virtualapp:p9
                                                                   at com.google.common.cache.LocalCache$Segment.a(:343160)
                                                                   at com.google.common.cache.LocalCache.a(:343922)
                                                                   at com.google.common.cache.LocalCache$LocalLoadingCache.c(:342960)
                                                                   at com.google.common.cache.LocalCache$LocalLoadingCache.d(:342962)
                                                                   at com.google.common.cache.ForwardingLoadingCache.d(:342830)
                                                                   at com.facebook.inject.FbInjector.get(:254368)
                                                                   at com.facebook.base.activity.FbFragmentActivity.attachBaseContext(:89033)
                                                                   at android.app.Activity.attach(Activity.java:6188)
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2350)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                   at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                Caused by: java.lang.UnsupportedOperationException: Injector is not supported in process io.virtualapp:p9
                                                                   at com.facebook.inject.FbInjector.b(:254354)
                                                                   at com.facebook.inject.FbInjector$ContextContextScopeAwareInjectorCacheLoader.a(:254322)
                                                                   at com.google.common.cache.LocalCache$LoadingValueReference.a(:342928)
                                                                   at com.google.common.cache.LocalCache$Segment.a()
                                                                   at com.google.common.cache.LocalCache$Segment.b()
                                                                   at com.google.common.cache.LocalCache$Segment.a(:343152)
                                                                   at com.google.common.cache.LocalCache.a(:343922) 
                                                                   at com.google.common.cache.LocalCache$LocalLoadingCache.c(:342960) 
                                                                   at com.google.common.cache.LocalCache$LocalLoadingCache.d(:342962) 
                                                                   at com.google.common.cache.ForwardingLoadingCache.d(:342830) 
                                                                   at com.facebook.inject.FbInjector.get(:254368) 
                                                                   at com.facebook.base.activity.FbFragmentActivity.attachBaseContext(:89033) 
                                                                   at android.app.Activity.attach(Activity.java:6188) 
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2350) 
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                   at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
09-01 15:17:26.861 15788-15788/io.virtualapp:p9 I/Process: Sending signal. PID: 15788 SIG: 9
09-01 15:17:27.100 15843-15843/io.virtualapp:p9 D/VA-IO: Find the so name : <EMPTY>.
09-01 15:17:27.101 15843-15843/io.virtualapp:p9 E/VA-IO: Unable to open the .

麻烦帮忙看一下是哪里出了问题。

**Comment by renqingyou** [comment]
你的可以登录google play账号吗？

**Comment by piersguo** [comment]
最新代码已OK
