### ISSUE TITLE
Android6.0手机进入Add App选择列表选择任意一个应用均停止运行

### ISSUE THREAD

**Issue by piersguo** [asLody/VirtualApp#9]
Dear lody,

拉的最新代码，编译后运行在我Android6.0手机上，正常进入点击加号，在Add App列表界面选任意App报错，错误log如下，请麻烦看下，多谢！

07-12 07:56:21.926 11587-11587/io.virtualapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: io.virtualapp, PID: 11587
                                                               java.lang.NullPointerException: Attempt to read from field 'android.content.pm.ActivityInfo android.content.pm.ResolveInfo.activityInfo' on a null object reference
                                                                   at android.view.ViewRootImpl.isTargetPackage(ViewRootImpl.java:8092)
                                                                   at android.view.ViewRootImpl.scheduleTraversals(ViewRootImpl.java:1262)
                                                                   at android.view.ViewRootImpl.invalidateRectOnScreen(ViewRootImpl.java:1154)
                                                                   at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1131)
                                                                   at android.view.ViewGroup.invalidateChild(ViewGroup.java:5219)
                                                                   at android.view.View.invalidateInternal(View.java:12900)
                                                                   at android.view.View.invalidate(View.java:12860)
                                                                   at android.view.View.invalidate(View.java:12844)
                                                                   at android.widget.ListView.layoutChildren(ListView.java:1528)
                                                                   at android.widget.AbsListView.onTouchUp(AbsListView.java:4184)
                                                                   at android.widget.AbsListView.onTouchEvent(AbsListView.java:3924)
                                                                   at android.view.View.dispatchTouchEvent(View.java:9415)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2660)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2304)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
                                                                   at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2453)
                                                                   at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1772)
                                                                   at android.app.Activity.dispatchTouchEvent(Activity.java:2808)
                                                                   at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                   at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2414)
                                                                   at android.view.View.dispatchPointerEvent(View.java:9646)
                                                                   at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4743)
                                                                   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4601)
                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4106)
                                                                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4159)
                                                                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4125)
                                                                   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4271)
                                                                   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4133)
                                                                   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4328)
                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4106)
                                                                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4159)
                                                                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4125)
                                                                   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4133)
                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4106)
                                                                   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6560)
                                                                   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6534)
                                                                   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6477)
                                                                   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6732)
                                                                   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                   at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                   at android.os.MessageQueue.next(MessageQueue.java:328)
                                                               	at android.os.Looper.loop(

**Comment by piersguo** [comment]
同样，我在另外一台Android5.1手机上也报类似错误：
07-12 17:02:18.501 32670-32670/io.virtualapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: io.virtualapp, PID: 32670
                                                               java.lang.NullPointerException: Attempt to read from field 'android.content.pm.ActivityInfo android.content.pm.ResolveInfo.activityInfo' on a null object reference
                                                                   at android.view.ViewRootImpl.setView(ViewRootImpl.java:773)
                                                                   at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:289)
                                                                   at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                                                                   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3323)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2631)
                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:181)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                   at android.os.Looper.loop(Looper.java:194)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5663)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by dodola** [comment]
@piersguo 说一下手机品牌和rom吧，第一条日志略奇怪

**Comment by zhx00100** [comment]
ViewRootImpl.isTargetPackage(ViewRootImpl.java:某行)
源码并没有这个函数，ROM定制的吧

**Comment by dodola** [comment]
@zhx00100 说的是😂,我也没找到，所以说略奇怪

**Comment by piersguo** [comment]
恩，这个上海华勤研发的手机，ROM是定制的

**Comment by piersguo** [comment]
我看了5.1的源码，在ViewRootImpl.java 文件 setView()方法最下面增加这一部分定制修改:
/// M: [APP launch time enhancenment feature] Check the APP is home catrgory
                /// or not. @{
                if (mView != null && mContext != null) {
                    final String pkgName = mView.getContext().getPackageName();
                    Intent intent = new Intent(Intent.ACTION_MAIN);
                    intent.addCategory(Intent.CATEGORY_HOME);
                    ResolveInfo resolveInfo = mContext.getPackageManager().resolveActivity(intent,
                            PackageManager.MATCH_DEFAULT_ONLY);
                    if (resolveInfo == null || resolveInfo.activityInfo == null ||
                            resolveInfo.activityInfo.packageName == null) {
                        mIsTargetPackage = false;
                    }
                    mIsTargetPackage = (resolveInfo.activityInfo.packageName.equals(pkgName));
                }
                /// @}

最后这句 mIsTargetPackage = (resolveInfo.activityInfo.packageName.equals(pkgName)); 导致了activityInfo 空指针异常，这个activityInfo 没有被hook吗，应该从哪一块来修改，有什么思路？

**Comment by piersguo** [comment]
我看了下，这块代码是MTK加的，MTK芯片平台上ViewRootImpl.java 文件均有此类代码，在MTK 6.0的源码中，调用的是下面方法：
/**
     * Debug option, whether the view is in target package, used to reduce useless logs.
     *
     * @return
     */
    private boolean isTargetPackage() {
        if (mView == null) {
            return false;
        }
        final String pkgName = mView.getContext().getPackageName();
        /// M: [APP launch time enhancenment feature] If the package name equals to default
        /// launcher's package name, then return TRUE. @{
        Intent intent = new Intent(Intent.ACTION_MAIN);
        intent.addCategory(Intent.CATEGORY_HOME);
        ResolveInfo resolveInfo = mContext.getPackageManager().resolveActivity(intent,
                PackageManager.MATCH_DEFAULT_ONLY);
        /// @}
        return (resolveInfo.activityInfo.packageName.equals(pkgName));
    }
也是resolveInfo.activityInfo 为null，导致异常出错。

**Comment by dodola** [comment]
大概看了一下代码问题好像出现在IntentResolve 类的，这段，我看
```java
	if (intentFilter.hasCategory(Intent.CATEGORY_DEFAULT)) {
									ResolveInfo resolveInfo = newResolveInfo(flagInfo, intentFilter);
									resolveInfo.match = match;
									resolveInfo.isDefault = true;
									outList.add(resolveInfo);
								} else {
									// 只是匹配默认。这里也算匹配不上。
								}

```

**Comment by piersguo** [comment]
好的，多谢 dodola, 我在这块附近抓个log 看一下

**Comment by piersguo** [comment]
此问题我今天跟踪了下，发现是在resolveIntent时候传入的Intent仅包含action和category, 目前IntentResolver.resolveIntent 方法中没有处理到此类情况，所以报错。 
我今天试了下，如果改动如下，可以绕过此问题，但是不知道是否符合目前框架思路，请帮忙check下或者给出更好的解决方案:
public ResolveInfo resolveIntent(Intent intent, String resolvedType, int flags) {
		try {
			Intent backupIntent = new Intent(intent);
			Map<String, APKBundle> bundleMap = getPMS().getAllAPKBundles();
			List<ResolveInfo> infos = IntentResolver.resolveIntent(getContext(), bundleMap, backupIntent, resolvedType,
					flags);
			if (infos.size() > 0) {
				return IntentResolver.findBest(infos);
			} **else {
				// if no valid infos return back, then let host PM to process it
				return mPM.resolveActivity(intent, flags);
			}**
		} catch (Throwable e) {
			e.printStackTrace();
		}
		return null;
	}
增加了else部分处理
