### ISSUE TITLE
oppo r9的问题

### ISSUE THREAD

**Issue by WTree** [asLody/VirtualApp#91]
在 oppo r9 打开网易时，打不开，错误log如下：
   java.io.FileNotFoundException: /data/data/com.netease.newsreader.activity/files/netease_log.temp: open failed: EACCES (Permission denied)

**Comment by prife** [comment]
试试 https://github.com/prife/VirtualAppDoc/issues/2  最后一条评论

**Comment by prife** [comment]
添加上面的IOHook后，测试几分钟后VirtualApp服务进程崩溃，日志如下：
```
09-02 04:56:34.455 27341 27341 D AndroidRuntime: Shutting down VM
09-02 04:56:34.455 27341 27341 E AndroidRuntime: FATAL EXCEPTION: main
09-02 04:56:34.455 27341 27341 E AndroidRuntime: Process: io.virtualapp:x, PID: 27341
09-02 04:56:34.455 27341 27341 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.lody.virtual.client.stub.StubPendingService@4aecc4f with Intent { act=netease.pomelo.news.push.messageservice_V1 flg=0x4 cmp=io.virtualapp/com.lody.virtual.client.stub.StubPendingService (has extras) }: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=netease.pomelo.news.push.messageservice_V1 (has extras) }
09-02 04:56:34.455 27341 27341 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3027)
09-02 04:56:34.455 27341 27341 E AndroidRuntime:        at android.app.ActivityThread.-wrap17(ActivityThread.java)
09-02 04:56:34.455 27341 27341 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
09-02 04:56:34.455 27341 27341 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
09-02 04:56:34.455 27341 27341 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
09-02 04:56:34.455 27341 27341 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
09-02 04:56:34.455 27341 27341 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-02 04:56:34.455 27341 27341 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-02 04:56:34.455 27341 27341 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-02 04:56:34.455 27341 27341 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=netease.pomelo.news.push.messageservice_V1 (has extras) }
09-02 04:56:34.455 27341 27341 E AndroidRuntime:        at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1209)
09-02 04:56:34.455 27341 27341 E AndroidRuntime:        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1238)
09-02 04:56:34.455 27341 27341 E AndroidRuntime:        at android.app.ContextImpl.startService(ContextImpl.java:1222)
09-02 04:56:34.455 27341 27341 E AndroidRuntime:        at android.content.ContextWrapper.startService(ContextWrapper.java:581)
09-02 04:56:34.455 27341 27341 E AndroidRuntime:        at com.lody.virtual.client.stub.StubPendingService.onStartCommand(StubPendingService.java:22)
09-02 04:56:34.455 27341 27341 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010)
09-02 04:56:34.455 27341 27341 E AndroidRuntime:        ... 8 more
09-02 04:56:34.456   363 27279 W SocketClient: write error (Broken pipe)
```
